Repository dotnet/extensions, pull requests merged in 2019-08, with the labels that each got.

#2061 Use Utf8JsonReader in DotNetDispatcher
  src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/JSAsyncCallResult.cs
  src/JSInterop/Microsoft.JSInterop/src/JSRuntimeBase.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeBaseTest.cs
Labels: area-blazor, tell-mode

#2081 Fix GetResourcePrefix() that causes an issue with using Rootnamespace
  Extensions.sln
  src/Localization/Localization/src/ResourceManagerStringLocalizerFactory.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests/AssemblyInfo.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests/Controllers/ValuesController.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests/Microsoft.Extensions.Localization.RootNamespace.Tests.csproj
  src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests/Resources/Controllers/ValuesController.resx
  src/Localization/Localization/test/Microsoft.Extensions.Localization.RootNamespace.Tests/StringLocalizerOfTRootNamespaceTest.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/LocalizationServiceCollectionExtensionsTest.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/Microsoft.Extensions.Localization.Tests.csproj
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/Model.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerFactoryTest.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/ResourceManagerStringLocalizerTest.cs
  src/Localization/Localization/test/Microsoft.Extensions.Localization.Tests/StringLocalizerOfTTest.cs
Labels: area-localization

#2162 Use YAML stages
  azure-pipelines.yml
Labels: area-infrastructure

#2165 Update documentation for IHttpClientFactory
  src/HttpClientFactory/Http/src/IHttpClientFactory.cs
Labels: area-httpclientfactory

#2168 Fix unintended breaking change
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.csproj
Labels: area-filesystem, area-infrastructure, auto-merge, tell-mode

#2169 Remove internal new() constraints from options infrastructure
  src/Options/Options/ref/Microsoft.Extensions.Options.netstandard2.0.cs
  src/Options/Options/src/IOptions.cs
  src/Options/Options/src/IOptionsFactory.cs
  src/Options/Options/src/IOptionsSnapshot.cs
  src/Options/Options/src/Options.cs
  src/Options/Options/src/OptionsFactory.cs
  src/Options/Options/src/OptionsManager.cs
  src/Options/Options/src/OptionsMonitor.cs
  src/Options/Options/src/OptionsWrapper.cs
  src/Options/test/OptionsTest.cs
Labels: area-config

#2147 Fixed xmldoc references to Scoped in Singleton overloads for ServiceDescriptor.
  src/DependencyInjection/DI.Abstractions/src/ServiceDescriptor.cs
Labels: area-dependencyinjection

#2176 Special case Disposing DotNetObjectReferences
  src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netcoreapp3.0.cs
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRef.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRefManager.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRefOfT.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectReferenceJsonConverter.cs
  src/JSInterop/Microsoft.JSInterop/src/IDotNetObjectRef.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetObjectRefTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSInProcessRuntimeBaseTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeBaseTest.cs
Labels: area-blazor, tell-mode

#2177 Update HttpClientFactoryServiceCollectionExtensions.cs
  src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs
Labels: area-httpclientfactory

#2186 Cleanup to skip/flaky attributes
  src/Caching/SqlServer/test/SqlServerCacheWithDatabaseTest.cs
  src/Configuration/Config.Xml/test/XmlConfigurationTest.cs
  src/Configuration/test/Config.FunctionalTests/ConfigurationTests.cs
  src/DiagnosticAdapter/test/DiagnosticSourceAdapterTest.cs
  src/FileProviders/Physical/test/PhysicalFileProviderTests.cs
  src/Hosting/IntegrationTesting/src/xunit/SkipIfEnvironmentVariableNotEnabled.cs
  src/Hosting/IntegrationTesting/src/xunit/SkipOn32BitOSAttribute.cs
  src/Hosting/test/FunctionalTests/ShutdownTests.cs
  src/Logging/Logging.Testing/src/Xunit/LoggedConditionalFactDiscoverer.cs
  src/Logging/Logging.Testing/src/Xunit/LoggedConditionalTheoryDiscoverer.cs
  src/Logging/Logging.Testing/src/Xunit/LoggedTestFrameworkDiscoverer.cs
  src/Logging/Logging.Testing/src/Xunit/LoggedTestRunner.cs
  src/Logging/Logging.Testing/test/LoggedTestXunitTests.cs
  src/Logging/test/EventLogLoggerTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/TestPlatformHelper.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalFactAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalFactDiscoverer.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ConditionalTheoryDiscoverer.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/DockerOnlyAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/EnvironmentVariableSkipConditionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/FlakyAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/FlakyTestDiscoverer.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/FrameworkSkipConditionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/IEnvironmentVariable.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/ITestCondition.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/MinimumOsVersionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/OSSkipConditionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/OperatingSystems.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/RuntimeFrameworks.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkipOnCIAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkipOnHelixAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/SkippedTestCase.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/TestMethodExtensions.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/WindowsVersions.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/ConditionalFactTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/ConditionalTheoryTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/DockerTests.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/EnvironmentVariableSkipConditionTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/FlakyAttributeTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/OSSkipConditionAttributeTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/OSSkipConditionTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/SkipOnCITests.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/TestPlatformHelperTest.cs
Labels: tell-mode

#2163 Change JSInterop to avoid using async locals
  src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netcoreapp3.0.cs
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectReference.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectReferenceOfT.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetObjectReferenceJsonConverter.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetObjectReferenceJsonConverterFactory.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetObjectReferenceManager.cs
  src/JSInterop/Microsoft.JSInterop/src/JSInProcessRuntime.cs
  src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs
  src/JSInterop/Microsoft.JSInterop/src/JsonSerializerOptionsProvider.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetObjectReferenceTest.cs
  src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetObjectReferenceJsonConverterTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSInProcessRuntimeTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeTest.cs
  src/JSInterop/Microsoft.JSInterop/test/TestJSRuntime.cs
  src/JSInterop/Mono.WebAssembly.Interop/ref/Mono.WebAssembly.Interop.netstandard2.0.cs
  src/JSInterop/Mono.WebAssembly.Interop/src/MonoWebAssemblyJSRuntime.cs
Labels: area-blazor, tell-mode

#2190 Add support for netcoreapp5.0 to micro benchmarks
  src/Shared/src/BenchmarkRunner/DefaultCoreConfig.cs
Labels: area-infrastructure

#2188 Simplify JSRuntime method signature
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netcoreapp3.0.cs
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetInvocationInfo.cs
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetInvocationResult.cs
  src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs
  src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSInProcessRuntimeTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeTest.cs
  src/JSInterop/Microsoft.JSInterop/test/TestJSRuntime.cs
  src/JSInterop/Mono.WebAssembly.Interop/ref/Mono.WebAssembly.Interop.netstandard2.0.cs
  src/JSInterop/Mono.WebAssembly.Interop/src/MonoWebAssemblyJSRuntime.cs
Labels: area-blazor, tell-mode

#2193 Update SDK to preview 8
  global.json
Labels: area-infrastructure, tell-mode

#2191 Backport source build patches
  src/Analyzers/Async/src/Microsoft.DotNet.Analyzers.Async.csproj
  src/Logging/Logging.Analyzers/src/Microsoft.Extensions.Logging.Analyzers.csproj
  src/TargetingPack/Microsoft.Internal.Extensions.Refs/ref/Microsoft.Internal.Extensions.Refs.csproj
Labels: area-infrastructure, tell-mode

#2214 Update spelling in docs for Dependency Injection extensions
  src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs
Labels: area-httpclientfactory

#2099 Move exception to setter for UsePollingFileWatcher
  src/FileProviders/Physical/src/PhysicalFileProvider.cs
  src/FileProviders/Physical/test/PhysicalFileProviderTests.cs
Labels: area-filesystem

#2218 [release/3.0] Rebrand to rc1
  eng/Versions.props
Labels: area-infrastructure

#2210 Add switch to enable expected and unexpected arguments in any order
  src/Shared/src/CommandLineUtils/CommandLine/CommandLineApplication.cs
  src/Shared/test/CommandLineApplicationTests.cs
Labels: area-primitives, tell-mode

#2080 Fix #2044 by updating doc comment
  src/Hosting/Abstractions/src/IHostApplicationLifetime.cs
Labels: area-hosting

#2255 Fix typo
  src/HealthChecks/Abstractions/src/HealthReport.cs
Labels: area-healthchecks

#2250 Update Microsoft.Data.SqlClient version
  eng/Dependencies.props
Labels: area-infrastructure, ask-mode
