Repository dotnet/extensions, pull requests merged in 2019-07, with the labels that each got.

#1903 Update branding to preview 8
  eng/Versions.props
Labels: area-infrastructure

#1879 Allow sanitation of dotnet interop exceptions
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/JSRuntimeBase.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeBaseTest.cs
  src/Options/Options/ref/Microsoft.Extensions.Options.netstandard2.0.cs
Labels: area-mvc

#1915 Add InvokeAsync with cancellation token overload to IJSRuntime
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/IJSRuntime.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeTest.cs
Labels: area-mvc

#1907 Capture stack trace in FileConfigurationProvider
  src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs
Labels: area-config

#1916 Explicitly reference Roslyn compiler toolset version that will ship in preview 7
  Directory.Build.targets
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#1906 Improve systemd detection for pre-232 systemd
  src/Hosting/Systemd/src/SystemdHelpers.cs
Labels: area-hosting

#1975 Upload /TestResults files as artifacts
  azure-pipelines.yml
Labels: area-infrastructure

#1990 In JSInterop calls, use expected value for 'this'. Fixes #1477
  src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts
Labels: area-mvc

#2002 Bring back required export jsCallDispatcher.findJSFunction
  src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts
Labels: area-mvc

#2006 update version of SqlClient used by sql cache
  eng/Dependencies.props
  src/Caching/Caching.slnf
  src/Caching/SqlServer/test/Microsoft.Extensions.Caching.SqlServer.Tests.csproj
  src/Caching/SqlServer/test/SqlServerCacheWithDatabaseTest.cs
  src/Caching/SqlServer/test/run-db-tests.ps1
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/EnvironmentVariableSkipConditionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/EnvironmentVariableSkipConditionTest.cs
Labels: area-caching

#1945 Fix memory leak
  src/Logging/Logging.Console/src/ConsoleLoggerProvider.cs
  src/Logging/test/ConsoleLoggerTest.cs
Labels: area-logging

#2043 [JSInterop] Updates the JSInterop abstractions to better support logging and diagnostics.
  src/JSInterop/Microsoft.JSInterop.JS/src/src/Microsoft.JSInterop.ts
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/JSAsyncCallResult.cs
  src/JSInterop/Microsoft.JSInterop/src/JSRuntimeBase.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetObjectRefTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSInProcessRuntimeBaseTest.cs
  src/JSInterop/Microsoft.JSInterop/test/JSRuntimeBaseTest.cs
  src/JSInterop/Mono.WebAssembly.Interop/ref/Mono.WebAssembly.Interop.netstandard2.0.cs
  src/JSInterop/Mono.WebAssembly.Interop/src/MonoWebAssemblyJSRuntime.cs
Labels: area-mvc

#2053 Add logging for the hanging case when calling start/stop
  src/Hosting/Hosting/ref/Microsoft.Extensions.Hosting.netcoreapp3.0.cs
  src/Hosting/Hosting/ref/Microsoft.Extensions.Hosting.netstandard2.0.cs
  src/Hosting/Hosting/src/Internal/ConsoleLifetime.cs
  src/Hosting/Hosting/test/HostBuilderTests.cs
  src/Hosting/samples/GenericHostSample/ProgramNoDisposeHangs.cs
  src/Hosting/test/testassets/Microsoft.Extensions.Hosting.TestApp/Program.cs
Labels: area-hosting

#2049 Use JsonConverter for DotNetObjectRef
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.netstandard2.0.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRef.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRefJsonConverterFactory.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRefManager.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectRefOfT.cs
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectReferenceJsonConverter.cs
  src/JSInterop/Microsoft.JSInterop/src/IDotNetObjectRef.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetDispatcherTest.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetObjectRefTest.cs
  src/JSInterop/Microsoft.JSInterop/test/DotNetObjectReferenceJsonConverterTest.cs
  src/JSInterop/Microsoft.JSInterop/test/TestJSRuntime.cs
Labels: area-mvc, tell-mode

#2083 Update SDK to preview 7
  global.json
Labels: area-infrastructure

#2079 Catch all exceptions from Exit shutdown
  src/Logging/Logging.Console/src/ConsoleLoggerProcessor.cs
Labels: area-hosting, tell-mode

#2062 Correct GetHashCode behavior for StringValues
  src/Primitives/src/StringValues.cs
  src/Primitives/test/StringValuesTests.cs
Labels: area-primitives, tell-mode

#2087 Add link to PR fixing the latest issue we're working around
  eng/Workarounds.AfterArcade.targets
Labels: area-infrastructure

#2048 Wait for host to shutdown before marking service stopped
  src/Hosting/WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.netstandard2.0.cs
  src/Hosting/WindowsServices/src/WindowsServiceLifetime.cs
Labels: area-hosting

#2093 Update branding to 5.0.0-alpha1
  eng/Versions.props
Labels: area-infrastructure, blocked
