Repository dotnet/extensions, pull requests merged in 2019-11, with the labels that each got.

#2602 Update SDK
  global.json
Labels: area-infrastructure

#2630 Add startvs for each solution
  src/Analyzers/startvs.cmd
  src/Caching/startvs.cmd
  src/Configuration/startvs.cmd
  src/DependencyInjection/startvs.cmd
  src/Hosting/startvs.cmd
  src/JSInterop/startvs.cmd
  src/Logging/startvs.cmd
Labels: area-infrastructure

#2627 Add event name for hosting logs
  src/Hosting/Hosting/src/Internal/LoggerEventIds.cs
Labels: area-hosting

#2613 Mark packages stable for 3.1.0
  eng/Versions.props
Labels: area-infrastructure

#2637 Remove PatchConfig.props; ship everything
  Directory.Build.props
  Directory.Build.targets
  docs/PreparingPatchUpdates.md
  docs/ReferenceResolution.md
  eng/PatchConfig.props
  eng/Versions.props
Labels: area-infrastructure, servicing-approved

#2685 Revert "Update dependencies from https://github.com/dotnet/core-setup…
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#2687 Update baselines for 3.0.1 release
  eng/Baseline.Designer.props
  eng/Baseline.xml
Labels: area-infrastructure

#2663 Switch to Arcade model for PackageIcon
  Directory.Build.props
  NuGet.config
  packageIcon.png
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.csproj
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.multitarget.nuspec
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.netcoreapp3.0.nuspec
Labels: area-infrastructure

#2609 Cleanup nuget feeds
  NuGet.config
Labels: area-infrastructure

#2634 update jsinterop NPM package ID for 5.0
  src/JSInterop/Microsoft.JSInterop.JS/src/Microsoft.JSInterop.JS.npmproj
  src/JSInterop/Microsoft.JSInterop.JS/src/package-lock.json
  src/JSInterop/Microsoft.JSInterop.JS/src/package.json
Labels: area-mvc

#2703 Update branding to 3.1.1
  azure-pipelines.yml
  eng/Versions.props
Labels: area-infrastructure

#2705 Handle operating system shutdown by overriding OnShutdown()
  src/Hosting/WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.netstandard2.0.cs
  src/Hosting/WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.netstandard2.1.cs
  src/Hosting/WindowsServices/src/WindowsServiceLifetime.cs
Labels: area-hosting

#2626 Set ServiceName vis UseWindowsService
  src/Hosting/WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.netstandard2.0.cs
  src/Hosting/WindowsServices/ref/Microsoft.Extensions.Hosting.WindowsServices.netstandard2.1.cs
  src/Hosting/WindowsServices/src/WindowsServiceLifetime.cs
  src/Hosting/WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs
  src/Hosting/WindowsServices/src/WindowsServiceLifetimeOptions.cs
Labels: api-approved, area-hosting

#2730 Fix wrong parameter description
  src/Hosting/Abstractions/src/IHostLifetime.cs
Labels: area-hosting
