Repository dotnet/extensions, pull requests merged in 2019-09, with the labels that each got.

#2344 Fix packing on *nix systems
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.csproj
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.multitarget.nuspec
  src/FileProviders/Embedded/src/Microsoft.Extensions.FileProviders.Embedded.netcoreapp.nuspec
Labels: area-infrastructure

#2359 Update ref assembly generation to use DefaultNetCoreTargetFramework p…
  eng/targets/ReferenceAssembly.targets
  src/Caching/Abstractions/ref/Microsoft.Extensions.Caching.Abstractions.csproj
  src/Caching/Memory/ref/Microsoft.Extensions.Caching.Memory.csproj
  src/Configuration/Config.Abstractions/ref/Microsoft.Extensions.Configuration.Abstractions.csproj
  src/Configuration/Config.Binder/ref/Microsoft.Extensions.Configuration.Binder.csproj
  src/Configuration/Config.CommandLine/ref/Microsoft.Extensions.Configuration.CommandLine.csproj
  src/Configuration/Config.EnvironmentVariables/ref/Microsoft.Extensions.Configuration.EnvironmentVariables.csproj
  src/Configuration/Config.FileExtensions/ref/Microsoft.Extensions.Configuration.FileExtensions.csproj
  src/Configuration/Config.Ini/ref/Microsoft.Extensions.Configuration.Ini.csproj
  src/Configuration/Config.Json/ref/Microsoft.Extensions.Configuration.Json.csproj
  src/Configuration/Config.KeyPerFile/ref/Microsoft.Extensions.Configuration.KeyPerFile.csproj
  src/Configuration/Config.UserSecrets/ref/Microsoft.Extensions.Configuration.UserSecrets.csproj
  src/Configuration/Config.Xml/ref/Microsoft.Extensions.Configuration.Xml.csproj
  src/Configuration/Config/ref/Microsoft.Extensions.Configuration.csproj
  src/DependencyInjection/DI/ref/Microsoft.Extensions.DependencyInjection.csproj
  src/FileProviders/Abstractions/ref/Microsoft.Extensions.FileProviders.Abstractions.csproj
  src/FileProviders/Composite/ref/Microsoft.Extensions.FileProviders.Composite.csproj
  src/FileProviders/Embedded/ref/Microsoft.Extensions.FileProviders.Embedded.csproj
  src/FileProviders/Physical/ref/Microsoft.Extensions.FileProviders.Physical.csproj
  src/HealthChecks/Abstractions/ref/Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.csproj
  src/HealthChecks/HealthChecks/ref/Microsoft.Extensions.Diagnostics.HealthChecks.csproj
  src/Hosting/Abstractions/ref/Microsoft.Extensions.Hosting.Abstractions.csproj
  src/Hosting/Hosting/ref/Microsoft.Extensions.Hosting.csproj
  src/HttpClientFactory/Http/ref/Microsoft.Extensions.Http.csproj
  src/JSInterop/Microsoft.JSInterop/ref/Microsoft.JSInterop.csproj
  src/Localization/Abstractions/ref/Microsoft.Extensions.Localization.Abstractions.csproj
  src/Localization/Localization/ref/Microsoft.Extensions.Localization.csproj
  src/Logging/Logging.Configuration/ref/Microsoft.Extensions.Logging.Configuration.csproj
  src/Logging/Logging.Console/ref/Microsoft.Extensions.Logging.Console.csproj
  src/Logging/Logging.Debug/ref/Microsoft.Extensions.Logging.Debug.csproj
  src/Logging/Logging.EventLog/ref/Microsoft.Extensions.Logging.EventLog.csproj
  src/Logging/Logging.EventSource/ref/Microsoft.Extensions.Logging.EventSource.csproj
  src/Logging/Logging.TraceSource/ref/Microsoft.Extensions.Logging.TraceSource.csproj
  src/Logging/Logging/ref/Microsoft.Extensions.Logging.csproj
  src/Options/ConfigurationExtensions/ref/Microsoft.Extensions.Options.ConfigurationExtensions.csproj
  src/Options/DataAnnotations/ref/Microsoft.Extensions.Options.DataAnnotations.csproj
  src/Options/Options/ref/Microsoft.Extensions.Options.csproj
  src/Primitives/ref/Microsoft.Extensions.Primitives.csproj
  src/WebEncoders/ref/Microsoft.Extensions.WebEncoders.csproj
Labels: area-infrastructure, tell-mode

#2342 Add support for JSInvokable methods on generic types
  src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs
  src/JSInterop/Microsoft.JSInterop/test/Infrastructure/DotNetDispatcherTest.cs
Labels: area-blazor

#2372 Add null check for DotNetObjectReference
  src/JSInterop/Microsoft.JSInterop/src/DotNetObjectReference.cs
Labels: tell-mode

#2378 Update branding to 2.1.14
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  version.props
Labels: area-platform

#2379 Update branding to 2.2.8
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  version.props
Labels: area-platform

#2392 Update branding to 3.0.1
  eng/PatchConfig.props
  eng/Versions.props
  eng/targets/ResolveReferences.targets
  src/TargetingPack/Microsoft.Internal.Extensions.Refs/ref/Microsoft.Internal.Extensions.Refs.csproj
Labels: area-platform

#2399 Update package baseline
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/tools/BaselineGenerator/BaselineGenerator.csproj
Labels: area-infrastructure

#2421 Update branding to 3.1.0-preview2
  eng/Versions.props
Labels: area-platform
