Repository dotnet/extensions, pull requests merged in 2019-12, with the labels that each got.

#2727 Pin dependency on Microsoft.Netcore.App refpack to 3.1.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#2738 Fix MaxOsVersion on Ubuntu
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/MaximumOSVersionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/MaximumOSVersionAttributeTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/MaximumOSVersionTest.cs
Labels: area-infrastructure

#2734 IsSystemdService: make check stricter to avoid false positives
  src/Hosting/Systemd/src/SystemdHelpers.cs
Labels: area-hosting, breaking-change

#2675 doc improvements
  src/DependencyInjection/DI/src/DefaultServiceProviderFactory.cs
  src/HttpClientFactory/Polly/src/PolicyHttpMessageHandler.cs
Labels: area-dependencyinjection, area-httpclientfactory

#2737 Build implementation projects against ref assemblies
  eng/targets/ResolveReferences.targets
  src/Configuration/Config.Ini/test/Microsoft.Extensions.Configuration.Ini.Tests.csproj
  src/Configuration/Config.Json/test/Microsoft.Extensions.Configuration.Json.Tests.csproj
  src/Configuration/Config.KeyPerFile/test/Microsoft.Extensions.Configuration.KeyPerFile.Tests.csproj
  src/Configuration/Config.NewtonsoftJson/test/Microsoft.Extensions.Configuration.NewtonsoftJson.Tests.csproj
  src/Configuration/Config.UserSecrets/test/Microsoft.Extensions.Configuration.UserSecrets.Tests.csproj
  src/Configuration/Config.Xml/test/Microsoft.Extensions.Configuration.Xml.Tests.csproj
  src/Configuration/test/Config.FunctionalTests/Microsoft.Extensions.Configuration.FunctionalTests.csproj
  src/Configuration/testassets/Test.Common/Microsoft.Extensions.Configuration.Test.Common.csproj
  src/HealthChecks/HealthChecks/test/Microsoft.Extensions.Diagnostics.HealthChecks.Tests.csproj
  src/Hosting/Hosting/test/Microsoft.Extensions.Hosting.Tests.csproj
  src/Hosting/Systemd/test/Microsoft.Extensions.Hosting.Systemd.Tests.csproj
  src/Hosting/WindowsServices/test/Microsoft.Extensions.Hosting.WindowsServices.Tests.csproj
  src/Hosting/test/FunctionalTests/Microsoft.Extensions.Hosting.FunctionalTests.csproj
  src/Hosting/test/testassets/Microsoft.Extensions.Hosting.TestApp/Microsoft.Extensions.Hosting.TestApp.csproj
  src/HttpClientFactory/Http/test/Microsoft.Extensions.Http.Tests.csproj
  src/HttpClientFactory/Polly/test/Microsoft.Extensions.Http.Polly.Tests.csproj
  src/Logging/Logging.AzureAppServices/test/Microsoft.Extensions.Logging.AzureAppServices.Tests.csproj
  src/Logging/Logging.EventSource/test/Microsoft.Extensions.Logging.EventSource.Tests.csproj
  src/Logging/test/Microsoft.Extensions.Logging.Tests.csproj
  src/WebEncoders/test/Microsoft.Extensions.WebEncoders.Tests.csproj
Labels: area-infrastructure

#2497 [release/3.0] Use Microsoft.NETCore.App.Internal for runtime version
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#2755 Remove version checks from OSSkipCondition
  src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.net46.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.netstandard2.0.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/OSSkipConditionAttribute.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/xunit/WindowsVersions.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/OSSkipConditionAttributeTest.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/OSSkipConditionTest.cs
Labels: area-infrastructure

#2753 [release/3.0] Stabilize package versions
  eng/Versions.props
Labels: area-infrastructure

#2754 [release/3.1] Stabilize package versions
  eng/Versions.props
Labels: area-infrastructure

#2786 Switch to label.N form for pre-release label
  eng/Versions.props
Labels: area-infrastructure
