Repository dotnet/extensions, pull requests merged in 2019-02, with the labels that each got.

#1067 fixup! Make KillProcesses.ps1 consistent with file in aspnet/AspNetCore
  eng/scripts/KillProcesses.ps1
Labels: area-infrastructure

#952 Wrapped SqlCommand and SqlDataReader in using statement
  src/Caching/SqlServer/src/DatabaseOperations.cs
Labels: area-caching

#1107 Add component detection step to builds
  azure-pipelines.yml
Labels: area-infrastructure

#988 ConfigurePrimaryHttpMessageHandler<T> uses builder name
  src/HttpClientFactory/Http/src/DependencyInjection/HttpClientBuilderExtensions.cs
Labels: area-httpclientfactory

#1169 Move to latest Xunit packages
  eng/Dependencies.props
Labels: area-infrastructure
