Repository dotnet/extensions, pull requests merged in 2020-10, with the labels that each got.

#3607 Turn on stable flag
  eng/Versions.props
Labels: * NO MERGE *, area-infrastructure

#3614 Update branding to 3.1.10
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#3569 Fix some issues with background thread compilation
  src/DependencyInjection/DI/src/ServiceLookup/DynamicServiceProviderEngine.cs
Labels: area-dependencyinjection, servicing-approved

#2806 Performance improvement by cleaning code and query tuning
  src/Caching/SqlServer/src/Columns.cs
  src/Caching/SqlServer/src/DatabaseOperations.cs
  src/Caching/SqlServer/src/MonoDatabaseOperations.cs
  src/Caching/SqlServer/src/SqlQueries.cs
Labels: area-caching, source-remaining-in-extensions

#3628 Update branding to 2.1.24
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Dependencies.props
  eng/PatchConfig.props
  korebuild-lock.txt
  version.props
Labels: area-infrastructure, tell-mode

#3655 [master] Disable validation stages
  azure-pipelines.yml
Labels: area-infrastructure

#3658 Removed unnecessary assignment and allocation
  src/Caching/StackExchangeRedis/src/RedisCache.cs
Labels: area-caching
