Repository dotnet/extensions, pull requests merged in 2020-03, with the labels that each got.

#3045 Do not pack M.AspNetCore.Testing
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/Microsoft.AspNetCore.Testing.csproj
Labels: area-infrastructure

#2927 [master] Switch to Windows Server queues
  azure-pipelines.yml
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/MaximumOSVersionTest.cs
Labels: area-infrastructure

#3061 Update branding to preview3
  eng/Versions.props
Labels: area-infrastructure

#3040 Remove Serilog dependency in extensions
  azure-pipelines.yml
  src/Caching/Memory/test/CapacityTests.cs
  src/Caching/Memory/test/Microsoft.Extensions.Caching.Memory.Tests.csproj
  src/Hosting/IntegrationTesting/src/Microsoft.Extensions.Hosting.IntegrationTesting.csproj
  src/Hosting/test/FunctionalTests/Microsoft.Extensions.Hosting.FunctionalTests.csproj
  src/Hosting/test/FunctionalTests/ShutdownTests.cs
  src/Logging/Logging.Testing/src/AssemblyTestLog.cs
  src/Logging/Logging.Testing/src/CollectDumpAttribute.cs
  src/Logging/Logging.Testing/src/DumpCollector/DumpCollector.Windows.cs
  src/Logging/Logging.Testing/src/DumpCollector/DumpCollector.cs
  src/Logging/Logging.Testing/src/LoggedTest/ILoggedTest.cs
  src/Logging/Logging.Testing/src/LoggedTest/LoggedTest.cs
  src/Logging/Logging.Testing/src/LoggedTest/LoggedTestBase.cs
  src/Logging/Logging.Testing/src/Microsoft.Extensions.Logging.Testing.csproj
  src/Logging/Logging.Testing/src/TestFrameworkFileLoggerAttribute.cs
  src/Logging/Logging.Testing/src/build/Microsoft.Extensions.Logging.Testing.props
  src/Logging/Logging.Testing/test/AssemblyTestLogTests.cs
  src/Logging/Logging.Testing/test/LoggedTestXunitTests.cs
  src/Logging/Logging.Testing/test/Microsoft.Extensions.Logging.Testing.Tests.csproj
Labels: area-infrastructure, area-logging

#3058 fix #3057 by removing Config.AzureKeyVault
  Extensions.sln
  eng/ProjectReferences.props
  src/Configuration/Config.AzureKeyVault/Directory.Build.props
  src/Configuration/Config.AzureKeyVault/ref/Microsoft.Extensions.Configuration.AzureKeyVault.csproj
  src/Configuration/Config.AzureKeyVault/ref/Microsoft.Extensions.Configuration.AzureKeyVault.netstandard2.0.cs
  src/Configuration/Config.AzureKeyVault/samples/EnvironmentSecretManager.cs
  src/Configuration/Config.AzureKeyVault/samples/KeyVaultSample.csproj
  src/Configuration/Config.AzureKeyVault/samples/Program.cs
  src/Configuration/Config.AzureKeyVault/samples/settings.json
  src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationExtensions.cs
  src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationOptions.cs
  src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationProvider.cs
  src/Configuration/Config.AzureKeyVault/src/AzureKeyVaultConfigurationSource.cs
  src/Configuration/Config.AzureKeyVault/src/DefaultKeyVaultSecretManager.cs
  src/Configuration/Config.AzureKeyVault/src/IKeyVaultClient.cs
  src/Configuration/Config.AzureKeyVault/src/IKeyVaultSecretManager.cs
  src/Configuration/Config.AzureKeyVault/src/KeyVaultClientWrapper.cs
  src/Configuration/Config.AzureKeyVault/src/Microsoft.Extensions.Configuration.AzureKeyVault.csproj
  src/Configuration/Config.AzureKeyVault/src/Properties/AssemblyInfo.cs
  src/Configuration/Config.AzureKeyVault/test/AzureKeyVaultConfigurationTest.cs
  src/Configuration/Config.AzureKeyVault/test/Microsoft.Extensions.Configuration.AzureKeyVault.Tests.csproj
  src/Configuration/Configuration.sln
  src/Configuration/Configuration.slnf
Labels: area-config

#3066 [master] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: area-infrastructure

#3067 [release/5.0 preview2] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#2957 Fix LoggingEventSource to handle null strings
  src/Logging/Logging.EventSource/src/LoggingEventSource.cs
  src/Logging/Logging.EventSource/src/Microsoft.Extensions.Logging.EventSource.csproj
  src/Logging/Logging.EventSource/test/EventSourceLoggerTest.cs
Labels: area-logging

#3094 Revert SDK version
  global.json
Labels: area-infrastructure

#2940 [Host] Allow disabling reloadOnChange for Host's CreateDefaultBuilder
  src/Hosting/Hosting/src/Host.cs
  src/Hosting/Hosting/test/HostTests.cs
Labels: area-hosting, auto-merge

#3097 Remove dependency on netstandard.library
  eng/Version.Details.xml
  eng/Versions.props
  eng/Workarounds.AfterArcade.targets
Labels: area-infrastructure

#3068 [release/3.1] Update hosted and BYOC agents used in our builds
  azure-pipelines.yml
Labels: * NO MERGE *, area-infrastructure, tell-mode

#3069 [release/2.1] Update hosted and BYOC agents used in our builds
  eng/templates/default-build.yml
Labels: * NO MERGE *, area-infrastructure, tell-mode

#3113 Update branding to 2.1.18
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  version.props
Labels: opened-during-migration

#3128 Update branding to preview4
  eng/Versions.props
Labels: area-infrastructure, opened-during-migration, tell-mode
