Repository dotnet/extensions, pull requests merged in 2020-02, with the labels that each got.

#2925 Fix DefaultHttpClientFactory log message typo
  src/HttpClientFactory/Http/src/DefaultHttpClientFactory.cs
Labels: area-httpclientfactory

#2808 Add ReloadOnChange to KeyPerFile configuration provider
  src/Configuration/Config.KeyPerFile/ref/Microsoft.Extensions.Configuration.KeyPerFile.netcoreapp.cs
  src/Configuration/Config.KeyPerFile/ref/Microsoft.Extensions.Configuration.KeyPerFile.netstandard2.0.cs
  src/Configuration/Config.KeyPerFile/src/KeyPerFileConfigurationBuilderExtensions.cs
  src/Configuration/Config.KeyPerFile/src/KeyPerFileConfigurationProvider.cs
  src/Configuration/Config.KeyPerFile/src/KeyPerFileConfigurationSource.cs
  src/Configuration/Config.KeyPerFile/test/KeyPerFileTests.cs
Labels: api-approved, area-config

#2741 Add more client factory overloads
  src/HttpClientFactory/Http/ref/Microsoft.Extensions.Http.netcoreapp.cs
  src/HttpClientFactory/Http/ref/Microsoft.Extensions.Http.netstandard2.0.cs
  src/HttpClientFactory/Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs
  src/HttpClientFactory/Http/test/DependencyInjection/HttpClientFactoryServiceCollectionExtensionsTest.cs
Labels: api-approved, area-httpclientfactory

#2964 Typo in comment: who's => whose
  src/Logging/Logging.Abstractions/src/ILoggerT.cs
Labels: area-logging

#2963 Clarify doc-comments in IHostApplicationLifetime
  src/Hosting/Abstractions/src/IHostApplicationLifetime.cs
Labels: area-hosting

#2929 [release/3.1] Switch to Windows Server queues
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#2900 [release/3.1] Pin dependency on 2 CoreFx packages
  eng/Version.Details.xml
Labels: area-infrastructure, tell-mode

#2936 Revert "Revert "Remove ref project from Microsoft.AspNetCore.Testing""
  Directory.Build.props
  eng/ProjectReferences.props
  src/Hosting/IntegrationTesting/src/Microsoft.Extensions.Hosting.IntegrationTesting.csproj
  src/Logging/Logging.Testing/src/Microsoft.Extensions.Logging.Testing.csproj
  src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.csproj
  src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.net46.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/ref/Microsoft.AspNetCore.Testing.netstandard2.0.cs
  src/TestingUtils/Microsoft.AspNetCore.Testing/src/Microsoft.AspNetCore.Testing.csproj
  src/TestingUtils/Microsoft.AspNetCore.Testing/test/Microsoft.AspNetCore.Testing.Tests.csproj
Labels: area-infrastructure, tell-mode

#2899 [release/3.0] Pin dependency on Microsoft.Win32.Registry
  eng/Version.Details.xml
Labels: area-infrastructure, tell-mode

#2970 Update branding to 2.1.17
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  version.props
Labels: area-infrastructure

#2928 [release/2.1] Switch to Windows Server queues
  eng/templates/default-build.yml
Labels: area-infrastructure, tell-mode

#2980 Document that StringValue ctor accepts a null string
  src/Primitives/src/StringValues.cs
Labels: area-primitives

#2989 [release/3.1] Update baselines
  eng/Baseline.Designer.props
  eng/Baseline.xml
Labels: area-infrastructure, tell-mode

#2994 Make Mono.WebAssembly.Interop non-shipping
  Extensions.sln
  eng/ProjectReferences.props
  src/JSInterop/JSInterop.slnf
  src/JSInterop/Mono.WebAssembly.Interop/Directory.Build.props
  src/JSInterop/Mono.WebAssembly.Interop/ref/Mono.WebAssembly.Interop.csproj
  src/JSInterop/Mono.WebAssembly.Interop/ref/Mono.WebAssembly.Interop.netstandard2.0.cs
  src/JSInterop/Mono.WebAssembly.Interop/src/InternalCalls.cs
  src/JSInterop/Mono.WebAssembly.Interop/src/Mono.WebAssembly.Interop.csproj
  src/JSInterop/Mono.WebAssembly.Interop/src/MonoWebAssemblyJSRuntime.cs
Labels: area-infrastructure, tell-mode

#3024 Fix closure allocation in scope DisposeAsync
  src/DependencyInjection/DI/src/ServiceLookup/ServiceProviderEngineScope.cs
Labels: area-dependencyinjection
