Repository dotnet/extensions, pull requests merged in 2020-04, with the labels that each got.

#3149 Update README.md
  README.md
Labels: area-infrastructure, auto-merge

#3151 [release/3.1] Don't run Code Check in official builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#3152 [release/5.0-preview3] Don't run Code Check in official builds
  azure-pipelines.yml
Labels: area-infrastructure, tell-mode

#3168 Pin 2 CoreFx dependencies
  eng/Version.Details.xml
  eng/Versions.props
Labels: tell-mode

#3190 Update branding to preview5
  eng/Versions.props
Labels: area-infrastructure

#3191 Use newer post-build.yml than Arcade provides
  eng/common/templates/post-build/post-build.yml
Labels: area-infrastructure
