Repository dotnet/extensions, pull requests merged in 2020-08, with the labels that each got.

#3393 Update branding to 3.1.8
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  global.json
  src/TargetingPack/Microsoft.Internal.Extensions.Refs/ref/Microsoft.Internal.Extensions.Refs.csproj
Labels: area-infrastructure, tell-mode

#3398 Update branding to 2.1.22
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  version.props
Labels: area-infrastructure, tell-mode

#3404 [release/3.1] Add CPD strict dependencies for aspnetcore-tooling
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#3417 [release/3.1] Add dependencies for CPD strict in aspnetcore
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure, tell-mode

#3424 [release/3.1] Downgrade packages when building ref/ projects
  eng/Versions.props
Labels: area-infrastructure, auto-merge, tell-mode
