Repository dotnet/extensions, pull requests merged in 2020-05, with the labels that each got.

#3215 updated readme
  README.md
Labels: area-infrastructure

#3229 Move SDL validation to ringed release
  azure-pipelines.yml
  eng/sdl-tsa-vars.config
Labels: area-infrastructure

#3232 Remove me from codeowners 😭
  .github/CODEOWNERS
Labels: auto-merge

#3242 Disable publishing during Linux builds
  azure-pipelines.yml
Labels: area-infrastructure

#3243 Update branding to Preview6
  eng/Versions.props
Labels: area-infrastructure

#3249 Update branding to 3.1.5
  NuGet.config
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#3201 [release/3.1] Move SDL validation to ringed release
  azure-pipelines.yml
  eng/sdl-tsa-vars.config
Labels: area-infrastructure, tell-mode
