Repository dotnet/extensions, pull requests merged in 2021-02, with the labels that each got.

#3825 Update branding to 3.1.13
  NuGet.config
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure

#3818 Disable producing Micorosft.Extensions.Hosting packages in extensions repo
  src/Hosting/Systemd/src/Microsoft.Extensions.Hosting.Systemd.csproj
  src/Hosting/WindowsServices/src/Microsoft.Extensions.Hosting.WindowsServices.csproj
Labels: area-infrastructure

#3827 Update branding to 2.1.26
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/PatchConfig.props
  eng/Sources.props
  korebuild-lock.txt
  version.props
Labels: area-infrastructure, auto-merge

#3833 Dead end the Microsoft.Extensions.Configuration.NewtonsoftJson package
  Extensions.sln
  README.md
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/ProjectReferences.props
  eng/Versions.props
  src/Configuration/Config.NewtonsoftJson/Directory.Build.props
  src/Configuration/Config.NewtonsoftJson/src/Microsoft.Extensions.Configuration.NewtonsoftJson.csproj
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonConfigurationExtensions.cs
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonConfigurationFileParser.cs
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonConfigurationProvider.cs
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonConfigurationSource.cs
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonStreamConfigurationProvider.cs
  src/Configuration/Config.NewtonsoftJson/src/NewtonsoftJsonStreamConfigurationSource.cs
  src/Configuration/Config.NewtonsoftJson/src/Resources.resx
  src/Configuration/Config.NewtonsoftJson/test/ArrayTest.cs
  src/Configuration/Config.NewtonsoftJson/test/ConfigurationProviderExtensions.cs
  src/Configuration/Config.NewtonsoftJson/test/ConfigurationProviderTestBase.cs
  src/Configuration/Config.NewtonsoftJson/test/Microsoft.Extensions.Configuration.NewtonsoftJson.Tests.csproj
  src/Configuration/Config.NewtonsoftJson/test/NewtonsoftConfigurationProviderJsonTest.cs
  src/Configuration/Config.NewtonsoftJson/test/NewtonsoftJsonConfigurationExtensionsTest.cs
  src/Configuration/Config.NewtonsoftJson/test/NewtonsoftJsonConfigurationTest.cs
  src/Configuration/Config.NewtonsoftJson/test/TestStreamHelpers.cs
  src/Configuration/Configuration.slnf
  src/Configuration/Directory.Build.props
  src/Configuration/README.md
  src/Configuration/startvs.cmd
Labels: area-config
