Repository dotnet/extensions, pull requests merged in 2021-04, with the labels that each got.

#3856 Update branding to 3.1.15
  eng/Versions.props
Labels: area-infrastructure

#3855 [release/2.1] Update branding to 2.1.28
  eng/Dependencies.props
  eng/PatchConfig.props
  eng/templates/default-build.yml
  src/Caching/Memory/test/CapacityTests.cs
  version.props
Labels: area-infrastructure, tell-mode

#3854 Backport of Allow increased log level filtering for event source logger
  src/Logging/Logging.EventSource/src/LoggingEventSource.cs
  src/Logging/Logging.EventSource/test/EventSourceLoggerTest.cs
Labels: area-logging, servicing-approved

#3859 [release/2.1] Credentials fix
  src/Configuration/Config.UserSecrets/test/ConfigurationExtensionTest.cs
Labels: area-config, area-infrastructure, tell-mode

#3865 Code merge, baseline and SDK update
  NuGet.config
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure, auto-merge

#3866 [release/2.1] Bump some versions
  eng/Baseline.Designer.props
  eng/Baseline.xml
  eng/Dependencies.props
  korebuild-lock.txt
  version.props
Labels: area-infrastructure, tell-mode

#3868 Update CI to use ubuntu18.04
  azure-pipelines.yml
  src/Hosting/Systemd/test/Microsoft.Extensions.Hosting.Systemd.Tests.csproj
  src/Hosting/Systemd/test/UseSystemdTests.cs
Labels: area-infrastructure, tell-mode
