Repository dotnet/extensions, pull requests merged in 2023-11, with the labels that each got.

#4651 Fix system.network.state dimension value
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsCounters.cs
Labels: work in progress :construction:

#4658 Improve sensitive data detection when logging records
  docs/list-of-diagnostics.md
  src/Generators/Microsoft.Gen.Logging/Parsing/DiagDescriptors.cs
  src/Generators/Microsoft.Gen.Logging/Parsing/Parser.LogProperties.cs
  src/Generators/Microsoft.Gen.Logging/Parsing/Parser.Records.cs
  src/Generators/Microsoft.Gen.Logging/Parsing/Parser.cs
  src/Generators/Microsoft.Gen.Logging/Parsing/Resources.Designer.cs
  src/Generators/Microsoft.Gen.Logging/Parsing/Resources.resx
  src/Generators/Microsoft.Gen.Logging/Parsing/SymbolLoader.cs
  src/Shared/DiagnosticIds/DiagnosticIds.cs
  test/Generators/Microsoft.Gen.Logging/Generated/SensitiveRecordTests.cs
  test/Generators/Microsoft.Gen.Logging/TestClasses/SensitiveRecordExtensions.cs
  test/Generators/Microsoft.Gen.Logging/Unit/AttributeParserTests.cs
  test/Generators/Microsoft.Gen.Logging/Unit/LogParserUtilitiesTests.cs
  test/Generators/Microsoft.Gen.Logging/Unit/ParserTests.LogProperties.cs
  test/Generators/Microsoft.Gen.Logging/Unit/ParserTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/AcceptanceTest.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/WindowsCountersTests.cs
Labels: area-telemetry

#4660 Add Microsoft.Extensions.Compliance.Testing readme
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/README.md
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Redaction/IRedactionBuilder.cs
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Redaction/IRedactorProvider.cs
  src/Libraries/Microsoft.Extensions.Compliance.Redaction/README.md
  src/Libraries/Microsoft.Extensions.Compliance.Redaction/RedactionExtensions.cs
  src/Libraries/Microsoft.Extensions.Compliance.Testing/FakeRedactionBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.Compliance.Testing/README.md
  src/Libraries/Microsoft.Extensions.Compliance.Testing/RedactorRequested.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/LoggingOptions.cs
Labels: waiting-author-feedback :mailbox_with_no_mail:

#4674 Readme for Microsoft.Extensions.Http.Diagnostics
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Microsoft.Extensions.Http.Diagnostics.csproj
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/README.md
Labels: area-telemetry

#4606 Update SDK to 23523.1
  global.json
  src/Shared/Pools/PooledListPolicy.cs
Labels: blocked
