Repository dotnet/extensions, pull requests merged in 2023-06, with the labels that each got.

#4058 Don't publish Microsoft.AspNetCore.Testing
  src/Libraries/Microsoft.AspNetCore.Testing/Microsoft.AspNetCore.Testing.csproj
Labels: area-infrastructure

#4059 Don't publish Microsoft.AspNetCore.Testing (#4058)
  src/Libraries/Microsoft.AspNetCore.Testing/Microsoft.AspNetCore.Testing.csproj
Labels: area-infrastructure

#4067 Fix docs warnings
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxResourceUtilizationCounters.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationExtensions.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsUtilizationExtensions.cs
  src/Libraries/Microsoft.Extensions.Http.Resilience/Hedging/Routing/IRequestRoutingStrategyFactory.cs
  src/Libraries/Microsoft.Extensions.Telemetry.Testing/Logging/FakeLoggerProvider.cs
  src/Libraries/System.Cloud.DocumentDb.Abstractions/IDocumentDatabase.cs
  src/Libraries/System.Cloud.DocumentDb.Abstractions/Model/RequestOptions.cs
  src/Libraries/System.Cloud.DocumentDb.Abstractions/Model/TableInfo.cs
  src/Libraries/System.Cloud.DocumentDb.Abstractions/Model/TableOptions.cs
Labels: documentation

#4024 Remove unclear Advance() method from FakeTimeProvider
  src/Libraries/Microsoft.Extensions.TimeProvider.Testing/FakeTimeProvider.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Testing.Tests/Logging/FakeLogCollectorTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Testing.Tests/Logging/FakeLoggerTests.cs
  test/Libraries/Microsoft.Extensions.TimeProvider.Testing.Tests/FakeTimeProviderTests.cs
Labels: waiting-on-team :wave:
