Repository dotnet/extensions, pull requests merged in 2024-10, with the labels that each got.

#5493 Doc updates to HybridCacheOptions
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/HybridCacheOptions.cs
Labels: area-caching-hybrid

#5497 Set WriteIndented=true for M.E.AI logging / telemetry / etc.
  src/Libraries/Microsoft.Extensions.AI/JsonDefaults.cs
Labels: area-AI

#5478 Allowing tags to start with _
  src/Generators/Microsoft.Gen.Metrics/Parser.cs
  test/Generators/Microsoft.Gen.Metrics/Unit/ParserTests.cs
Labels: area-telemetry

#5507 Use the same JsonSerializerOptions default in all locations.
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactoryCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI/JsonDefaults.cs
Labels: area-AI

#5508 Use the logging generator in LoggingChatClient / LoggingEmbeddingGenerator
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/LoggingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
Labels: area-AI

#5503 Avoid use of FormattableString when logging
  src/Generators/Microsoft.Gen.Logging/Emission/Emitter.Method.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/Log.cs
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Logging/LoggerMessageHelper.cs
Labels: area-fundamentals

#5509 Add comment about use of hashing in CachingHelpers
  src/Libraries/Microsoft.Extensions.AI/CachingHelpers.cs
Labels: area-AI

#5514 Improve CachingChatClient's coalescing of streaming updates
  src/Libraries/Microsoft.Extensions.AI.Abstractions/AdditionalPropertiesDictionary.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGenerationOptions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
Labels: area-AI

#5515 Add thread-safety comments about M.E.AI middleware components
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/IChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/IEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ConfigureOptionsChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/DistributedCachingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/LoggingEmbeddingGenerator.cs
Labels: area-AI

#5513 Expose an `AIJsonUtilities` class in M.E.AI and lower M.E.AI.Abstractions to STJv8
  eng/Versions.props
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionCallContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionCallHelpers.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/Microsoft.Extensions.AI.AzureAIInference.csproj
  src/Libraries/Microsoft.Extensions.AI.Ollama/JsonContext.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.csproj
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/DistributedCachingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/LoggingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.Utilities.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactoryCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/Libraries/Microsoft.Extensions.AI/Utilities/AIJsonSchemaCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI/Utilities/AIJsonUtilities.Defaults.cs
  src/Libraries/Microsoft.Extensions.AI/Utilities/AIJsonUtilities.Schema.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionCallContentTests..cs
Labels: area-AI

#5532 Update UseOpenTelemetry for latest genai spec updates
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatOptions.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClientBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGeneratorBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/Libraries/Microsoft.Extensions.AI/OpenTelemetryConsts.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/EmbeddingGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/OpenTelemetryChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Microsoft.Extensions.AI.Tests.csproj
Labels: area-AI

#5470 Use 8.0 era dependencies for non net9.0 TFMs
  eng/Version.Details.xml
  eng/Versions.props
  eng/packages/General-LTS.props
  eng/packages/General-net9.props
  eng/packages/General.props
  src/Libraries/Microsoft.AspNetCore.HeaderParsing/Microsoft.AspNetCore.HeaderParsing.csproj
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
Labels: area-fundamentals

#5536 Remove unnecessary ctors from FunctionResultContent
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionResultContent.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatMessageTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/StreamingChatCompletionUpdateTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionResultContentTests.cs
Labels: area-AI

#5535 Remove AIContent.ModelId, add StreamingChatCompletionUpdate.ModelId
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/StreamingChatCompletionUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIContent.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatMessageTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/AIContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/DataContentTests{T}.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionCallContentTests..cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionResultContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/TextContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/UsageContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
Labels: area-AI

#5550 Script to generate weekly digest
  .gitignore
  eng/scripts/Get-RepoDigest.ps1
  eng/scripts/repo-digest-template.html
Labels: area-infrastructure

#5561 Remove some defunct lazy init from chat clients
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
Labels: area-AI

#5563 Add EmbeddingGeneratorOptions.Dimensions
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGenerationOptions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Embeddings/EmbeddingGenerationOptionsTests.cs
Labels: area-AI

#5560 Structured output improvements (continuation of PR 5522)
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatCompletion{T}.cs
  src/Libraries/Microsoft.Extensions.AI/Utilities/AIJsonUtilities.Schema.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientStructuredOutputExtensionsTests.cs
Labels: area-AI

#5558 Update M.E.AI.AzureAIInference for its beta2 release
  eng/packages/General.props
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/Embedding.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIChatToolJson.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/JsonContext.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceEmbeddingGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/IntegrationTestHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
Labels: area-AI

#5580 Merge ResourceMonitoringOptions.Linux.cs into ResourceMonitoringOptions.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringOptions.Linux.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringOptions.cs
Labels: area-telemetry
