Repository dotnet/extensions, pull requests merged in 2024-11, with the labels that each got.

#5593 Improve AdditionalPropertiesDictionary
  src/Libraries/Microsoft.Extensions.AI.Abstractions/AdditionalPropertiesDictionary.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AdditionalPropertiesDictionaryTests.cs
Labels: area-AI

#5594 Add UseEmbeddingGenerationOptions
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ConfigureOptionsChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ConfigureOptionsChatClientBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/ConfigureOptionsEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/ConfigureOptionsEmbeddingGeneratorBuilderExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ConfigureOptionsChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/ConfigureOptionsEmbeddingGeneratorTests.cs
Labels: area-AI

#5467 HybridCache stability and logging improvements
  eng/packages/TestOnly.props
  eng/spellchecking_exclusions.dic
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.CacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.ImmutableCacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.L2.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.MutableCacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.Serialization.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.StampedeState.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.StampedeStateT.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/HybridCacheEventSource.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/InbuiltTypeSerializer.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/Log.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/RecyclableArrayBufferWriter.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Microsoft.Extensions.Compliance.Abstractions.csproj
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/HybridCacheEventSourceTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/LogCollector.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/Microsoft.Extensions.Caching.Hybrid.Tests.csproj
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/NullDistributedCache.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/SizeTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/TestEventListener.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/UnreliableL2Tests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Abstractions.Tests/Microsoft.Extensions.Telemetry.Abstractions.Tests.csproj
Labels: area-caching-hybrid

#5600 Assign ownership
  .github/CODEOWNERS
  src/Analyzers/Microsoft.Analyzers.Extra/Microsoft.Analyzers.Extra.csproj
  src/Analyzers/Microsoft.Analyzers.Local/Microsoft.Analyzers.Local.csproj
  src/Generators/Microsoft.Gen.ComplianceReports/Microsoft.Gen.ComplianceReports.csproj
  src/Generators/Microsoft.Gen.ContextualOptions/Microsoft.Gen.ContextualOptions.csproj
  src/Libraries/Microsoft.AspNetCore.Testing/Microsoft.AspNetCore.Testing.csproj
  src/Libraries/Microsoft.Extensions.AmbientMetadata.Application/Microsoft.Extensions.AmbientMetadata.Application.csproj
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Microsoft.Extensions.Compliance.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.Compliance.Redaction/Microsoft.Extensions.Compliance.Redaction.csproj
  src/Libraries/Microsoft.Extensions.Compliance.Testing/Microsoft.Extensions.Compliance.Testing.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.Common/Microsoft.Extensions.Diagnostics.HealthChecks.Common.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Microsoft.Extensions.Diagnostics.ResourceMonitoring.csproj
  src/Libraries/Microsoft.Extensions.Hosting.Testing/Microsoft.Extensions.Hosting.Testing.csproj
  src/Libraries/Microsoft.Extensions.Options.Contextual/Microsoft.Extensions.Options.Contextual.csproj
  src/Packages/Microsoft.Extensions.AuditReports/Microsoft.Extensions.AuditReports.csproj
  src/Packages/Microsoft.Extensions.StaticAnalysis/Microsoft.Extensions.StaticAnalysis.csproj
Labels: area-infrastructure

#5601 HybridCache: don't log cancellation as failure event
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.StampedeStateT.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/HybridCacheEventSource.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/HybridCacheEventSourceTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/TestEventListener.cs
Labels: area-telemetry, area-caching-hybrid

#5596 Add logging/activities to FunctionInvokingChatClient
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClientBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/LoggingHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
Labels: area-AI

#5614 Use ToChatCompletion in OpenTelemetryChatClient
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
Labels: area-AI

#5616 Use ToChatCompletion / ToStreamingChatCompletionUpdates in CachingChatClient
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/StreamingChatCompletionUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/StreamingChatCompletionUpdateExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatCompletionTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/StreamingChatCompletionUpdateExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
Labels: area-AI

#5618 Add DebuggerDisplay for DataContent
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs
Labels: area-AI

#5619 Expose options for making schema generation conformant with the subset accepted by OpenAI.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonSchemaCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactoryCreateOptions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-AI

#5597 Cache current process object to avoid performance hit
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Interop/ProcessInfo.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsSnapshotProvider.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/ProcessInfoTests.cs
Labels: area-resourcemonitoring

#5620 Fix namespace for IServiceCollection extensions
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientBuilderServiceCollectionExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/EmbeddingGeneratorBuilderServiceCollectionExtensions.cs
Labels: area-AI

#5628 Allow logging of body without modifying the actual response
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/Constants.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpRequestBodyReader.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpResponseBodyReader.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Microsoft.Extensions.Http.Diagnostics.csproj
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Logging/AcceptanceTests.cs
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Logging/HttpRequestBodyReaderTest.cs
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Logging/HttpResponseBodyReaderTest.cs
Labels: area-telemetry

#5589 Make ActivityBaggageLogScopeWrapper implements IEnumerable<KeyValuePair<string, object?>>
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/Import/LoggerFactoryScopeProvider.cs
Labels: area-telemetry

#5657 Add a [DebuggerDisplay] to GeneratedEmbeddings
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/GeneratedEmbeddings.cs
Labels: area-AI

#5656 Annotate private DebuggerDisplay props as DebuggerBrowsableState.Never
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseFormatJson.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/RequiredChatToolMode.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionCallContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/FunctionResultContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/UsageContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/UsageDetails.cs
Labels: area-AI

#5653 Fix M.E.AI argument tests to validate argument names
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGenerationOptions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatFinishReasonTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseFormatTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatRoleTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/DelegatingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/DataContentTests{T}.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionCallContentTests..cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Embeddings/DelegatingEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Embeddings/EmbeddingGenerationOptionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Embeddings/GeneratedEmbeddingsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientBuilderTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/EmbeddingGeneratorBuilderTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-AI

#5651 Remove duplicate GetCacheKey methods
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/CachingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/DistributedCachingEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/DistributedCachingEmbeddingGeneratorTest.cs
Labels: area-AI

#5658 Augment XML comments for AIFunctionFactory.Create
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
Labels: area-AI

#5652 Add AsBuilder extensions for IChatClient and IEmbeddingGenerator
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientBuilderChatClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/EmbeddingGeneratorBuilderEmbeddingGeneratorExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/EmbeddingGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ReducingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientBuilderTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ConfigureOptionsChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/LoggingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/OpenTelemetryChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/ConfigureOptionsEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/DistributedCachingEmbeddingGeneratorTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/EmbeddingGeneratorBuilderTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/LoggingEmbeddingGeneratorTests.cs
Labels: area-AI

#5663 Reduce a bit of LINQ in M.E.AI
  src/Libraries/Microsoft.Extensions.AI.Abstractions/AdditionalPropertiesDictionary.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatMessage.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/StreamingChatCompletionUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIContentExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
Labels: area-AI

#5650 Add anonymous chat clients / embedding generators
  eng/Versions.props
  eng/packages/General-LTS.props
  eng/packages/General-net9.props
  src/Libraries/Microsoft.Extensions.AI.Abstractions/README.md
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/AnonymousDelegatingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientBuilder.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/AnonymousDelegatingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/EmbeddingGeneratorBuilder.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/UseDelegateChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/UseDelegateEmbeddingGeneratorTests.cs
Labels: area-AI

#5654 Tweak CachingHelpers.GetCacheKey to clean up better on failure
  src/Libraries/Microsoft.Extensions.AI/CachingHelpers.cs
Labels: area-AI

#5682 Change UseLogging to accept an ILoggerFactory instead of ILogger
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClientBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/LoggingEmbeddingGeneratorBuilderExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/CapturingLogger.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Microsoft.Extensions.AI.Abstractions.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/Microsoft.Extensions.AI.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/LoggingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/LoggingEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Microsoft.Extensions.AI.Tests.csproj
Labels: area-AI

#5677 Expose a schema transformer on AIJsonSchemaCreateOptions.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonSchemaCreateContext.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonSchemaCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-AI

#5684 Update M.E.AI CHANGELOG.md for latest bits
  src/Libraries/Microsoft.Extensions.AI.Abstractions/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.Ollama/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.OpenAI/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI/CHANGELOG.md
Labels: area-AI

#5634 Add API allowing to disable retries for a given list of HTTP methods
  src/Libraries/Microsoft.Extensions.Http.Resilience/Polly/HttpRetryStrategyOptionsExtensions.cs
  test/Libraries/Microsoft.Extensions.Http.Resilience.Tests/Polly/HttpRetryStrategyOptionsExtensionsTests.cs
Labels: area-resilience

#5683 Improve FakeTimeProvider documentation, remove redundant tests
  src/Libraries/Microsoft.Extensions.TimeProvider.Testing/README.md
  test/Libraries/Microsoft.Extensions.TimeProvider.Testing.Tests/FakeTimeProviderTests.cs
  test/Libraries/Microsoft.Extensions.TimeProvider.Testing.Tests/TimerTests.cs
Labels: area-fundamentals
