Repository dotnet/extensions, pull requests merged in 2024-12, with the labels that each got.

#5670 Removes Experimental attribute from ResilienceHandler class
  scripts/MakeApiBaselines.ps1
  src/Libraries/Microsoft.Extensions.Http.Resilience/Microsoft.Extensions.Http.Resilience.csproj
  src/Libraries/Microsoft.Extensions.Http.Resilience/Microsoft.Extensions.Http.Resilience.json
  src/Libraries/Microsoft.Extensions.Http.Resilience/Resilience/ResilienceHandler.cs
Labels: area-resilience, api-approved

#5712 Update otel chat client / embedding generator for 1.29 draft of the spec
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatClientMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/StreamingChatCompletionUpdateExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGeneratorMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/Microsoft.Extensions.AI.AzureAIInference.csproj
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/Libraries/Microsoft.Extensions.AI/OpenTelemetryConsts.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientBuilderTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/OpenTelemetryChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/OpenTelemetryEmbeddingGeneratorTests.cs
Labels: area-AI

#5725 Update OpenAI dependency to 2.1.0
  eng/packages/General.props
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
Labels: area-AI

#5727 Add a few missing options to OpenAIChatclient.ToOpenAIOptions
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
Labels: area-AI

#5697 Add OpenAI serialization helper methods.
  eng/MSBuild/Shared.props
  src/Libraries/Microsoft.Extensions.AI.OpenAI/JsonModelHelpers.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatCompletionRequest.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIJsonContext.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatMessage.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMappers.StreamingChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAISerializationHelpers.cs
  src/Shared/ServerSentEvents/ArrayBuffer.cs
  src/Shared/ServerSentEvents/Helpers.cs
  src/Shared/ServerSentEvents/PooledByteBufferWriter.cs
  src/Shared/ServerSentEvents/README.md
  src/Shared/ServerSentEvents/SseFormatter.cs
  src/Shared/ServerSentEvents/SseItem.cs
  src/Shared/ServerSentEvents/SseItemParser.cs
  src/Shared/ServerSentEvents/SseParser.cs
  src/Shared/ServerSentEvents/SseParser_1.cs
  src/Shared/ServerSentEvents/ThrowHelper.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISerializationTests.cs
Labels: area-AI

#5732 Update Azure.AI.OpenAI version to 2.1.0
  eng/packages/TestOnly.props
Labels: area-AI

#5700 Bump code coverage
  eng/scripts/ValidateProjectCoverage.ps1
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Microsoft.Extensions.Diagnostics.Probes.csproj
Labels: area-infrastructure
