Repository dotnet/extensions, pull requests merged in 2025-08, with the labels that each got.

#6675 Fix one more version conflict on the docs transport package
  src/Packages/Microsoft.Internal.Extensions.DotNetApiDocs.Transport/Microsoft.Internal.Extensions.DotNetApiDocs.Transport.proj
Labels: area-ai-eval

#6674 Introduce metadata to identify built-in evaluation metrics
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Microsoft.Extensions.AI.Evaluation.Console.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/BLEUEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/F1Evaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/GLEUEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/Microsoft.Extensions.AI.Evaluation.NLP.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/CoherenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/CompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/EquivalenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/FluencyEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/GroundednessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/IntentResolutionEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/Microsoft.Extensions.AI.Evaluation.Quality.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceTruthAndCompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RetrievalEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/TaskAdherenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ToolCallAccuracyEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/Microsoft.Extensions.AI.Evaluation.Safety.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation/Utilities/BuiltInEvaluatorUtilities.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Tests/BuiltInEvaluatorUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Tests/Microsoft.Extensions.AI.Evaluation.Tests.csproj
Labels: area-ai-eval

#6682 Emit {OriginalFormat} in HttpClient logger
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/Log.cs
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Logging/AcceptanceTests.cs
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Logging/HttpClientLoggerTest.cs
Labels: area-telemetry

#6684 Update to OpenAI 2.3.0
  eng/packages/General.props
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIResponsesExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAISpeechToTextClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIConversionTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISpeechToTextClientTests.cs
Labels: area-ai

#6697 Bring back per library CHANGELOGS for M.E.AI
  src/Libraries/Microsoft.Extensions.AI.Abstractions/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.OpenAI/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI/CHANGELOG.md
Labels: area-ai

#6648 Add support for text-to-image
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/DelegatingImageGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/IImageGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/ImageGenerationOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/ImageGenerationRequest.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/ImageGenerationResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/ImageGeneratorExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Image/ImageGeneratorMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Defaults.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIImageGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Image/ConfigureOptionsImageGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Image/ConfigureOptionsImageGeneratorBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Image/ImageGeneratorBuilder.cs
  src/Libraries/Microsoft.Extensions.AI/Image/ImageGeneratorBuilderImageGeneratorExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Image/ImageGeneratorBuilderServiceCollectionExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Image/LoggingImageGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Image/LoggingImageGeneratorBuilderExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/DelegatingImageGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/ImageGenerationOptionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/ImageGenerationResponseTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/ImageGeneratorExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/ImageGeneratorMetadataTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Image/ImageGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestImageGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestJsonSerializerContext.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ImageGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/Microsoft.Extensions.AI.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/README.md
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIImageGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIImageGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Image/ConfigureOptionsImageGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Image/ImageGeneratorDependencyInjectionPatterns.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Image/LoggingImageGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Image/SingletonImageGeneratorExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Microsoft.Extensions.AI.Tests.csproj
Labels: area-ai

#6706 Reapply https://github.com/dotnet/extensions/pull/6205
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData-CSharp.Web/Components/Pages/Chat/Chat.razor
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Ollama_Qdrant.verified/aichatweb/aichatweb.Web/Components/Pages/Chat/Chat.razor
Labels: area-ai-templates

#6709 Update Azure.AI.OpenAI
  src/ProjectTemplates/GeneratedContent.targets
Labels: area-ai-templates

#6666 Add middleware for reducing chat history
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ReducingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ReducingChatClientBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatReduction/IChatReducer.cs
  src/Libraries/Microsoft.Extensions.AI/ChatReduction/MessageCountingChatReducer.cs
  src/Libraries/Microsoft.Extensions.AI/ChatReduction/SummarizingChatReducer.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/Microsoft.Extensions.AI.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ReducingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ReducingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatReduction/MessageCountingChatReducerTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatReduction/SummarizingChatReducerTests.cs
Labels: area-ai

#6715 Merge in 'release/9.8' branch
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#6722 Add model provider information to ChatTurnDetails
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ChatTurnDetails.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Microsoft.Extensions.AI.Evaluation.Reporting.json
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ResponseCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/SimpleChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ChatDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/EvalTypes.d.ts
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/ChatTurnDetailsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/ResponseCacheTester.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/ScenarioRunResultTests.cs
Labels: area-ai-eval

#6721 Fix GetResponseAsync<T> to look at the last message only
  src/Libraries/Microsoft.Extensions.AI/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatResponse{T}.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientStructuredOutputExtensionsTests.cs
Labels: area-ai

#6751 Introduce some helpers that perform heuristic matches to detect well known model hosts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Microsoft.Extensions.AI.Evaluation.Console.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ChatTurnDetails.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Microsoft.Extensions.AI.Evaluation.Reporting.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ResponseCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/SimpleChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/Microsoft.Extensions.AI.Evaluation.Safety.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation/Utilities/ModelInfo.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/AgentQualityEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/QualityEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/SafetyEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Tests/ModelInfoTests.cs
Labels: area-ai-eval
