Repository dotnet/extensions, pull requests merged in 2025-07, with the labels that each got.

#6557 Update GenAI otel impl for v1.35
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceImageEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceImageEmbeddingGeneratorTests.cs
Labels: area-ai

#6561 Update tokenizer algorithm to use is [..]
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/Common/SimpleWordTokenizer.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.NLP.Tests/SimpleTokenizerTests.cs
Labels: area-ai-eval

#6558 Add DistributedCachingChatClient/EmbeddingGenerator.AdditionalCacheKeyValues
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ResponseCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/CachingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/DistributedCachingEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.json
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/DistributedCachingEmbeddingGeneratorTest.cs
Labels: area-ai

#6566 Align EventId generation with M.E.Logging source-gen
  src/Generators/Microsoft.Gen.Logging/Emission/Emitter.Method.cs
  test/Generators/Microsoft.Gen.Logging/Generated/LogMethodTests.cs
  test/Generators/Microsoft.Gen.Logging/TestClasses/EventNameTestExtensions.cs
Labels: area-telemetry

#6565 Add DelegatingAIFunction
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/DelegatingAIFunction.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.json
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Functions/DelegatingAIFunctionTests.cs
Labels: area-ai

#6564 Add FunctionInvokingChatClient.FunctionInvoker delegate
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.json
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
Labels: area-ai

#6571 Use dnx instead of dotnet tool exec in MCP server template README
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/McpServer/McpServer-CSharp/README.md
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/mcpserver.Basic.verified/mcpserver/README.md
Labels: area-ai-templates

#6574 Add reporting tests that show NLP results.
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/BLEUEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/F1Evaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.NLP/GLEUEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationMetricExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Microsoft.Extensions.AI.Evaluation.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/NLPEvaluatorTests.cs
Labels: area-ai-eval

#6573 Branding updates for 9.8.0
  eng/Versions.props
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/CompatibilitySuppressions.xml
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.AzureOpenAI_Qdrant_Aspire.verified/aichatweb/aichatweb.ServiceDefaults/aichatweb.ServiceDefaults.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.AzureOpenAI_Qdrant_Aspire.verified/aichatweb/aichatweb.Web/aichatweb.Web.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Basic.verified/aichatweb/aichatweb.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.BasicAspire.verified/aichatweb/aichatweb.ServiceDefaults/aichatweb.ServiceDefaults.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.BasicAspire.verified/aichatweb/aichatweb.Web/aichatweb.Web.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Ollama_Qdrant.verified/aichatweb/aichatweb.ServiceDefaults/aichatweb.ServiceDefaults.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Ollama_Qdrant.verified/aichatweb/aichatweb.Web/aichatweb.Web.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.OpenAI_AzureAISearch.verified/aichatweb/aichatweb.csproj
Labels: area-ai-templates

#6554 Refactor Resource Monitoring
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/CompatibilitySuppressions.xml
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/Log.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringOptions.cs
  src/Shared/Instruments/ResourceUtilizationInstruments.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/AcceptanceTest.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationProviderTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/ResourceMonitoringOptionsTests.cs
Labels: area-telemetry

#6572 AIFunctionFactory: tolerate JSON string function parameters.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionFactory.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-ai

#6576 AIFunctionFactory: add test coverage for JSON comments.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionFactory.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-ai

#6577 Update M.E.AI.OpenAI for latest OpenAI release
  eng/packages/General.props
  src/Libraries/Microsoft.Extensions.AI.Abstractions/SpeechToText/SpeechToTextOptions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIAssistantChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIRealtimeConversationClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAISpeechToTextClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/Microsoft.Extensions.AI.OpenAI.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIAIFunctionConversionTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIAssistantChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIAssistantChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIResponseClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISpeechToTextClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISpeechToTextClientTests.cs
Labels: area-ai

#6578 Update McpServer template for 0.3.0-preview.2
  src/ProjectTemplates/GeneratedContent.targets
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/McpServer/McpServer-CSharp/Tools/RandomNumberTools.cs
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/mcpserver.Basic.verified/mcpserver/Tools/RandomNumberTools.cs
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/mcpserver.Basic.verified/mcpserver/mcpserver.csproj
Labels: area-ai-templates

#6219 Add netstandard2.0 compatibility to Microsoft.Extensions.Diagnostics.Testing and dependencies
  src/Libraries/Microsoft.Extensions.Diagnostics.Testing/Microsoft.Extensions.Diagnostics.Testing.csproj
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Microsoft.Extensions.Telemetry.Abstractions.csproj
Labels: area-telemetry

#6174 Simplify Http.Diagnostics
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Http/DownstreamDependencyMetadataManager.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Latency/HttpClientLatencyTelemetryExtensions.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Latency/Internal/HttpClientLatencyContext.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Latency/Internal/HttpLatencyTelemetryHandler.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Latency/Internal/HttpRequestLatencyListener.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpClientLogger.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpRequestBodyReader.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Logging/Internal/HttpResponseBodyReader.cs
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Microsoft.Extensions.Http.Diagnostics.csproj
  src/Libraries/Microsoft.Extensions.Http.Resilience/Microsoft.Extensions.Http.Resilience.csproj
  test/Libraries/Microsoft.Extensions.Http.Diagnostics.Tests/Latency/Internal/HttpRequestLatencyListenerTest.cs
Labels: area-telemetry

#6599 Bump FunctionInvokingChatClient.MaximumIterationsPerRequest from 10 to 40
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
Labels: area-ai

#6601 Expose M.E.AI.OpenAI input message conversions
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIAIFunctionConversionTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIConversionTests.cs
Labels: area-ai

#6586 Add memory usage metric
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/Log.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Log.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsContainerSnapshotProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsSnapshotProvider.cs
  src/Shared/Instruments/ResourceUtilizationInstruments.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization.Tests/ResourceHealthCheckExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/AcceptanceTest.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationProviderTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/WindowsContainerSnapshotProviderTests.cs
Labels: area-resourcemonitoring

#6606 Add schema version to server.json in MCP template
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/McpServer/McpServer-CSharp/.mcp/server.json
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/mcpserver.Basic.verified/mcpserver/.mcp/server.json
Labels: area-ai-templates

#6589 Merge release/9.7 into main
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#6596 Fix schema generation for Nullable<T> function parameters.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.Create.cs
  src/Shared/JsonSchemaExporter/JsonSchemaExporter.ReflectionHelpers.cs
  src/Shared/JsonSchemaExporter/JsonSchemaExporter.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AssertExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
  test/Shared/JsonSchemaExporter/TestData.cs
  test/Shared/JsonSchemaExporter/TestTypes.cs
Labels: area-ai

#6621 Add support for new Azure AI Foundry project type for Safety evals
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.UrlCacheKey.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServiceConfiguration.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/SafetyEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Settings.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/appsettings.json
Labels: area-ai-eval

#6616 Add DataContent.Name property
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIAnnotation.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIAnnotationExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIAnnotationKind.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIAnnotationReference.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.json
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/AIAnnotationReferenceTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/AIAnnotationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/AIContentAnnotationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/DataContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
Labels: area-ai

#6627 Fix handling of multiple responses messages
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIResponseClientTests.cs
Labels: area-ai

#6629 Expose additional chat model conversion helpers
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIAssistantsExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIChatExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIRealtimeExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIResponsesExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIAssistantsChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIAssistantChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIConversionTests.cs
Labels: area-ai

#6655 Remove `Microsoft.Extensions.AI.Ollama`
  src/Libraries/Microsoft.Extensions.AI.Ollama/JsonContext.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.csproj
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.json
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatRequest.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatRequestMessage.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatResponseMessage.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaEmbeddingRequest.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaEmbeddingResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionCallContent.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionResultContent.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionTool.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionToolCall.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionToolParameter.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionToolParameters.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaRequestOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaTool.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaToolCall.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaUtilities.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/README.md
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/Microsoft.Extensions.AI.Ollama.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaEmbeddingGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/TestJsonSerializerContext.cs
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/IntegrationTestHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/OllamaSharpChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/OllamaSharpEmbeddingGeneratorIntegrationTests.cs
Labels: area-ai

#6615 Add [Description] to DataContent.Uri
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/DataContent.cs
Labels: area-ai

#6653 Fix duplicate solution file when creating an AI Chat Web app from VS
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/.template.config/template.json
Labels: area-ai-templates

#6657 Add ChatMessage.CreatedAt
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatMessage.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.json
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatMessageTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseUpdateExtensionsTests.cs
Labels: area-ai

#6661 Add FunctionInvokingChatClient.AdditionalTools
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.json
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Microsoft.Extensions.AI.Tests.csproj
Labels: area-ai

#6662 Add more openai conversion helpers
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIChatExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIResponsesExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIAssistantsChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIConversionTests.cs
Labels: area-ai

#6667 Add OriginalRepoCommitHash to assemblies
  Directory.Build.targets
Labels: area-infrastructure

#6669 Include a trivial items keyword if missing.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.Create.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
Labels: area-ai

#6671 Add resolution of function parameter level data annotation attributes.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.Create.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
Labels: area-ai

#6672 Fix issue with NetSourceIndexStage1 for dependency conflict versions
  src/Packages/Microsoft.Internal.Extensions.DotNetApiDocs.Transport/Microsoft.Internal.Extensions.DotNetApiDocs.Transport.proj
Labels: area-ai-eval

#6636 Expose streaming conversion utility methods
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIChatExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/MicrosoftExtensionsAIResponsesExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponsesChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIConversionTests.cs
Labels: area-ai

#6673 Couple of fixes for MEAI.Evaluation
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/MetricCard.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatClient.cs
Labels: area-ai-eval
