Repository dotnet/extensions, pull requests merged in 2025-02, with the labels that each got.

#5785 HybridCache : implement the tag expiration feature
  eng/MSBuild/LegacySupport.props
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/BufferChunk.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.CacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.Debug.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.ImmutableCacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.L2.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.MutableCacheItem.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.Serialization.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.Stampede.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.StampedeStateT.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.TagInvalidation.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultHybridCache.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/HybridCacheEventSource.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/HybridCachePayload.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/Log.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/RecyclableArrayBufferWriter.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/TagSet.cs
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/BufferReleaseTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/DistributedCacheTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/FunctionalTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/HybridCacheEventSourceTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/L2Tests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/LocalInvalidationTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/Microsoft.Extensions.Caching.Hybrid.Tests.csproj
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/Options.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/PayloadTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/SampleUsage.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/SerializerTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/ServiceConstructionTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/SizeTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/StampedeTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/TagSetTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/UnreliableL2Tests.cs
Labels: area-caching-hybrid

#5844 Move ResourceUtilizationInstruments to Shared project
  eng/MSBuild/Shared.props
  src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.HealthChecks.ResourceUtilization/ResourceUtilizationHealthCheck.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/Network/LinuxNetworkMetrics.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Microsoft.Extensions.Diagnostics.ResourceMonitoring.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Network/WindowsNetworkMetrics.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsContainerSnapshotProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsSnapshotProvider.cs
  src/Shared/Instruments/README.md
  src/Shared/Instruments/ResourceUtilizationInstruments.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/AcceptanceTest.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxCountersTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxNetworkMetricsTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationProviderTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/WindowsContainerSnapshotProviderTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/WindowsNetworkMetricsTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/WindowsSnapshotProviderTests.cs
Labels: area-resourcemonitoring

#5826 Move AIFunction parameter schematization from parameter level to function level.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionParameterMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionReturnParameterMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIChatToolJson.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaFunctionToolParameters.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIRealtimeExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Functions/AIFunctionMetadataTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Functions/AIFunctionParameterMetadataTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Functions/AIFunctionReturnParameterMetadataTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISerializationTests.cs
Labels: area-AI

#5869 Update to {Azure.AI.}OpenAI 2.2.0-beta.1
  eng/packages/General.props
  eng/packages/TestOnly.props
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIAssistantClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatMessage.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIRealtimeTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISerializationTests.cs
Labels: area-ai

#5870 Rename IChatClient members and corresponding types
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatClientExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatClientMetadata.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseUpdateExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatRole.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/DelegatingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/IChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/UsageContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/README.md
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Defaults.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/README.md
  src/Libraries/Microsoft.Extensions.AI.Ollama/OllamaChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Ollama/README.md
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIAssistantClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatCompletionRequest.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMapper.ChatMessage.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIModelMappers.StreamingChatCompletion.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAISerializationHelpers.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/README.md
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/AnonymousDelegatingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientBuilder.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatResponse{T}.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ConfigureOptionsChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/LoggingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatClientExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseUpdateExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseUpdateTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/DelegatingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/TestJsonSerializerContext.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/IntegrationTestHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/CallCountingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/PromptBasedFunctionCallingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ReducingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/OllamaChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAISerializationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientStructuredOutputExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ConfigureOptionsChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/LoggingChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/OpenTelemetryChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/UseDelegateChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/LoggingEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/TestJsonSerializerContext.cs
Labels: area-ai

#5871 Enable API compat validation
  Directory.Build.props
  eng/MSBuild/Packaging.targets
  eng/Versions.props
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/Microsoft.Extensions.AI.AzureAIInference.csproj
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/ProjectTemplates/Directory.Build.props
Labels: area-infrastructure

#5864 Generalise how package version isn't stabilized for dev/preview stages
  eng/MSBuild/ProjectStaging.targets
  src/Generators/Microsoft.Gen.MetricsReports/Directory.Build.props
  src/Generators/Microsoft.Gen.MetricsReports/Microsoft.Gen.MetricsReports.csproj
  src/Libraries/Microsoft.AspNetCore.Testing/Directory.Build.props
  src/Libraries/Microsoft.AspNetCore.Testing/Microsoft.AspNetCore.Testing.csproj
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Microsoft.Extensions.AI.Abstractions.csproj
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/Microsoft.Extensions.AI.AzureAIInference.csproj
  src/Libraries/Microsoft.Extensions.AI.Ollama/Microsoft.Extensions.AI.Ollama.csproj
  src/Libraries/Microsoft.Extensions.AI.OpenAI/Microsoft.Extensions.AI.OpenAI.csproj
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Microsoft.Extensions.Caching.Hybrid.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Directory.Build.props
  src/Libraries/Microsoft.Extensions.Diagnostics.Probes/Microsoft.Extensions.Diagnostics.Probes.csproj
  src/Libraries/Microsoft.Extensions.Hosting.Testing/Directory.Build.props
  src/Libraries/Microsoft.Extensions.Hosting.Testing/Microsoft.Extensions.Hosting.Testing.csproj
  src/Libraries/Microsoft.Extensions.Options.Contextual/Directory.Build.props
  src/Libraries/Microsoft.Extensions.Options.Contextual/Microsoft.Extensions.Options.Contextual.csproj
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/Microsoft.Extensions.AI.Templates.csproj
Labels: area-infrastructure

#5896 Remove the `ref int` parameter from `ChatConversationEvaluator.CanRenderAsync()`
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ChatConversationEvaluator.cs
Labels: area-ai-eval

#5902 Couple of minor changes around doc comments
  .github/CODEOWNERS
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ChatConversationEvaluator.cs
Labels: area-ai-eval

#5903 Build evaluation report in CI and when enabled
  eng/pipelines/templates/BuildAndTest.yml
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Directory.Build.targets
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Microsoft.Extensions.AI.Evaluation.Console.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Microsoft.Extensions.AI.Evaluation.Reporting.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/Directory.Build.targets
Labels: area-ai-eval

#5894 Fix analyzer reference in AuditReports package
  src/Generators/Microsoft.Gen.MetadataExtractor/Microsoft.Gen.MetadataExtractor.csproj
  src/Packages/Microsoft.Extensions.AuditReports/Microsoft.Extensions.AuditReports.csproj
Labels: area-compliance

#5874 Use Environment.WorkingSet in WindowsSnapshotProvider
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/WindowsSnapshotProvider.cs
Labels: area-resourcemonitoring

#5919 Make MetadataExtractor & MetricsReports in Microsoft.Extensions.AuditReports create directories [Same as ComplianceReport]
  src/Generators/Microsoft.Gen.MetadataExtractor/MetadataReportsGenerator.cs
  src/Generators/Microsoft.Gen.MetricsReports/MetricsReportsGenerator.cs
  test/Generators/Microsoft.Gen.MetadataExtractor/Unit/GeneratorTests.cs
Labels: area-telemetry

#5887 Introduce type converter for DataClassification
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Classification/DataClassification.cs
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/Classification/DataClassificationTypeConverter.cs
  src/Libraries/Microsoft.Extensions.Compliance.Abstractions/README.md
  test/Libraries/Microsoft.Extensions.Compliance.Abstractions.Tests/Classification/DataClassificationTypeConverterTests.cs
  test/Libraries/Microsoft.Extensions.Compliance.Abstractions.Tests/Microsoft.Extensions.Compliance.Abstractions.Tests.csproj
Labels: area-compliance

#5945 Use structured output for RTC evaluator
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ChatConversationEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/Microsoft.Extensions.AI.Evaluation.Quality.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceTruthAndCompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/SingleNumericMetricEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/Utilities/JsonOutputFixer.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/AdditionalContextTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/EndToEndTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/RelevanceTruthAndCompletenessEvaluatorTests.cs
Labels: area-ai-eval

#5932 Upgrade `slngen` to avoid crash with newer versions of VS
  .config/dotnet-tools.json
Labels: area-infrastructure

#5948 Update coverage baseline
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/Microsoft.Extensions.AI.Evaluation.Quality.csproj
Labels: area-ai-eval

#5926 Make sure npm build tasks happen reliably and only once.
  Directory.Build.props
  eng/pipelines/templates/BuildAndTest.yml
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Directory.Build.targets
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Formats/Html/HtmlReportWriter.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Microsoft.Extensions.AI.Evaluation.Reporting.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/Directory.Build.targets
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/EmbeddingTests.cs
Labels: area-ai-eval

#5969 Enable building and signing VSIX for extension
  azure-pipelines-public.yml
  azure-pipelines.yml
  eng/pipelines/templates/BuildAndTest.yml
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/build.ps1
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/logo.png
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/overview.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/sign-vsix.js
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/tasks/PublishAIEvaluationReport/package.json
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/vss-extension.json
Labels: area-ai-eval

#5973 Move Azure DevOps extension build until after the transport package build
  eng/pipelines/templates/BuildAndTest.yml
Labels: area-ai-eval

#5978 Explicitly specify VSIX file to sign to fix internal official build.
  azure-pipelines-public.yml
  azure-pipelines.yml
  eng/Signing.props
Labels: area-infrastructure, area-ai-eval

#5972 Remove gitignore from AI chat template
  .gitattributes
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/.gitignore
Labels: area-ai

#5974 Addressing dogfooding feedback, adding GitHub Models support
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/.template.config/template.json
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/Components/Pages/Chat/Chat.razor
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/Data/Example_Emergency_Survival_Kit.pdf
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/Data/Example_GPS_Watch.pdf
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/README.md
Labels: area-ai

#5982 Move example PDFs into wwwroot/Data
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/wwwroot/Data/Example - Emergency Survival Kit.pdf
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/wwwroot/Data/Example - GPS Watch.pdf
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/wwwroot/Data/Example_Emergency_Survival_Kit.pdf
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/wwwroot/Data/Example_GPS_Watch.pdf
Labels: area-ai

#5979 HybridCache JSON serialization improvements
  src/Libraries/Microsoft.Extensions.Caching.Hybrid/Internal/DefaultJsonSerializerFactory.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/BufferReleaseTests.cs
  test/Libraries/Microsoft.Extensions.Caching.Hybrid.Tests/SerializerTests.cs
Labels: enhancement, area-caching-hybrid

#5574 Add logging sampling
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Microsoft.AspNetCore.Diagnostics.Middleware.csproj
  src/Libraries/Microsoft.Extensions.Http.Diagnostics/Microsoft.Extensions.Http.Diagnostics.csproj
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Sampling/LoggingSampler.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLogger.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLoggerFactory.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/Import/LoggerInformation.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/LoggerConfig.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Microsoft.Extensions.Telemetry.csproj
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/ILogSamplingFilterRule.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/LogSamplingRuleSelector.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSampler.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSamplerConfigureOptions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSamplerFilterRule.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSamplerOptions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSamplerOptionsValidator.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/SamplingLoggerBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Sampling/TraceBasedSampler.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Logging/ExtendedLoggerFactoryTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Logging/ExtendedLoggerTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Sampling/LogSamplingRuleSelectorTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Sampling/RandomProbabilisticSamplerTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Sampling/SamplingLoggerBuilderExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Sampling/TraceBasedSamplerTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/appsettings.json
Labels: area-telemetry

#5993 Add context to getting started with using Azure AI Search
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData.Web/README.md
Labels: area-ai
