Repository dotnet/extensions, pull requests merged in 2025-04, with the labels that each got.

#6209 Mirror integration tests for OllamaSharp
  eng/packages/General.props
  test/Libraries/Microsoft.Extensions.AI.Ollama.Tests/IntegrationTestHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/OllamaSharpChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.OllamaSharp.Integration.Tests/OllamaSharpEmbeddingGeneratorIntegrationTests.cs
Labels: area-ai

#6227 Update otel semantic convention version in comment
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
Labels: area-ai

#6226 Update README with Logging sampling information
  src/Libraries/Microsoft.Extensions.Telemetry/README.md
Labels: area-telemetry

#6230 Lower M.E.AI dependencies on .NET 8 and lower back to 8.0.x
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/AnonymousDelegatingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatResponse{T}.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/Embeddings/OpenTelemetryEmbeddingGenerator.cs
  src/Libraries/Microsoft.Extensions.AI/Microsoft.Extensions.AI.csproj
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AssertExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Microsoft.Extensions.AI.Abstractions.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Shared/JsonSchemaExporter/TestData.cs
  test/Shared/JsonSchemaExporter/TestTypes.cs
Labels: area-ai

#6222 Add TextReasoningContent
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIContent.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/TextReasoningContent.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseUpdateExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/TextReasoningContentTests.cs
Labels: area-ai

#6231 Use ErrorContent in OpenAIResponseChatClient
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/ErrorContent.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/ErrorContentTests.cs
Labels: area-ai

#6225 OpenAI: Parse detail additional property
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/Microsoft.Extensions.AI.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/IntegrationTestHelpers.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/Microsoft.Extensions.AI.OpenAI.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
  test/Shared/ImageDataUri/ImageDataUri.cs
  test/Shared/ImageDataUri/dotnet.png
Labels: area-ai

#6233 Branding updates for 9.5
  eng/Versions.props
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Basic.verified/aichatweb/aichatweb.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.BasicAspire--aspire.verified/aichatweb/aichatweb.ServiceDefaults/aichatweb.ServiceDefaults.csproj
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.BasicAspire--aspire.verified/aichatweb/aichatweb.Web/aichatweb.Web.csproj
Labels: area-infrastructure

#6239 In telemetry, treat AdditionalProperties as sensitive
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/OpenTelemetryChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/OpenTelemetryChatClientTests.cs
Labels: area-ai

#6237 Use SHA384 and make key more explicit
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ResponseCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/DistributedCachingChatClientTest.cs
Labels: area-ai

#6241 Disable STJ default reflection and fix a number of failing tests.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Defaults.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/AssertExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseFormatTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/ErrorContentTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/FunctionCallContentTests..cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Microsoft.Extensions.AI.Abstractions.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/ChatClientStructuredOutputExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Microsoft.Extensions.AI.Tests.csproj
  test/Shared/JsonSchemaExporter/TestTypes.cs
Labels: area-ai

#6243 Add button to report to download dataset as JSON
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
Labels: area-ai-eval

#6251 Only display tags from the latest execution
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScoreNodeHistory.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Styles.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/TagsDisplay.tsx
Labels: area-ai-eval

#6252 Avoid duplicate data in downloaded report file
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
Labels: area-ai-eval

#6257 Update dev-server data import to reflect runtime import quirks
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/html-report/src/main.tsx
Labels: area-ai-eval

#5635 Add logging buffering
  eng/MSBuild/Shared.props
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/IncomingRequestLogBuffer.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/IncomingRequestLogBufferHolder.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerIncomingRequestLoggingBuilderExtensions.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerRequestLogBufferManager.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerRequestLogBufferingConfigureOptions.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerRequestLogBufferingOptions.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerRequestLogBufferingOptionsCustomValidator.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Buffering/PerRequestLogBufferingOptionsValidator.cs
  src/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware/Microsoft.AspNetCore.Diagnostics.Middleware.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.Testing/Logging/FakeLogger.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.Testing/Microsoft.Extensions.Diagnostics.Testing.csproj
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Buffering/GlobalLogBuffer.cs
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Buffering/LogBuffer.cs
  src/Libraries/Microsoft.Extensions.Telemetry.Abstractions/Buffering/PerRequestLogBuffer.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/BufferedLoggerProxy.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalBuffer.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalBufferLoggingBuilderExtensions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalLogBufferManager.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalLogBufferingConfigureOptions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalLogBufferingOptions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalLogBufferingOptionsCustomValidator.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/GlobalLogBufferingOptionsValidator.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/LogBufferingFilterRule.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/LogBufferingFilterRuleSelector.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Buffering/StringifyComprarer.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLogger.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/ExtendedLoggerFactory.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/LoggerConfig.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/LoggingEnrichmentExtensions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Logging/LoggingRedactionExtensions.cs
  src/Libraries/Microsoft.Extensions.Telemetry/Microsoft.Extensions.Telemetry.csproj
  src/Shared/LogBuffering/DeserializedLogRecord.cs
  src/Shared/LogBuffering/SerializedLogRecord.cs
  src/Shared/LogBuffering/SerializedLogRecordFactory.cs
  src/Shared/Pools/PoolFactory.cs
  src/Shared/Pools/PooledListWithCapacityPolicy.cs
  src/Shared/Shared.csproj
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/Buffering/PerIncomingRequestLoggingBuilderExtensionsTests.cs
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/Buffering/PerRequestLogBufferingOptionsConfigureOptionsTests.cs
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/Buffering/PerRequestLogBufferingOptionsCustomValidatorTests.cs
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/Logging/AcceptanceTests.cs
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/Logging/HeaderNormalizerTests.cs
  test/Libraries/Microsoft.AspNetCore.Diagnostics.Middleware.Tests/appsettings.json
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Buffering/GlobalBufferLoggerBuilderExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Buffering/GlobalLogBufferingConfigureOptionsTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Buffering/GlobalLogBufferingOptionsCustomValidatorTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Buffering/LogBufferingFilterRuleTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Logging/ExtendedLoggerTests.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/Logging/Utils.cs
  test/Libraries/Microsoft.Extensions.Telemetry.Tests/appsettings.json
  test/Shared/Throw/DoubleTests.cs
Labels: area-telemetry

#6265 Add test for optional parameters being required with RequireAllProperties
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
Labels: area-ai

#6262 Add fuzzy filtering to the evaluation reports
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ReportContext.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScenarioTree.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Summary.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package-lock.json
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package.json
Labels: area-ai-eval

#6272 Updating package validation version to 9.4.0
  eng/Versions.props
Labels: area-infrastructure

#6276 Adding reference to an unsupported built-in tool on OpenAI Chat API no longer throws
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
Labels: area-ai

#6269 Update M.E.AI changelogs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.Ollama/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI.OpenAI/CHANGELOG.md
  src/Libraries/Microsoft.Extensions.AI/CHANGELOG.md
Labels: area-ai

#6275 Add missing reference to M.E.AI.OpenAI in chat template
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData-CSharp.Web/ChatWithCustomData-CSharp.Web.csproj.in
Labels: area-ai-templates

#6281 Fix two paramref tags
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ChatDetailsExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationMetricExtensions.cs
Labels: area-ai-eval

#6277 Support response caching for safety evaluators
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/EquivalenceEvaluatorContext.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/GroundednessEvaluatorContext.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceTruthAndCompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ReportingConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ChatDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/CodeVulnerabilityEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentHarmEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.UrlCacheKey.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.UrlConfigurationComparer.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServiceConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServiceConfigurationExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServicePayloadUtilities.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/EvaluationMetricExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/GroundednessProEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/GroundednessProEvaluatorContext.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/HateAndUnfairnessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/IndirectAttackEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ProtectedMaterialEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/SelfHarmEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/SexualEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/UngroundedAttributesEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/UngroundedAttributesEvaluatorContext.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ViolenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationContext.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/SafetyEvaluatorTests.cs
Labels: area-ai-eval

#6286 Display images in conversation for report
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ConversationDetails.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/EvalTypes.d.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Styles.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Summary.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/AIContentExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ChatMessageExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ChatResponseExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServicePayloadUtilities.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ProtectedMaterialEvaluator.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Microsoft.Extensions.AI.Evaluation.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/SafetyEvaluatorTests.cs
Labels: area-ai-eval

#6256 Augment UseDistributedCache XML docs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/DistributedCachingChatClientBuilderExtensions.cs
Labels: area-ai

#6261 Update README.md with keyless auth guidance
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData-CSharp.Web/README.md
Labels: area-ai-templates

#6255 Augment AIFunctionFactory.Create XML docs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
Labels: area-ai

#6295 Rename EmbeddingGeneratorExtensions.GenerateEmbedding extension methods
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGeneratorExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/README.md
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/ChatWithCustomData-CSharp.Web/Services/SemanticSearch.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Embeddings/EmbeddingGeneratorExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/EmbeddingGeneratorIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/DistributedCachingEmbeddingGeneratorTest.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/LoggingEmbeddingGeneratorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Embeddings/OpenTelemetryEmbeddingGeneratorTests.cs
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.Basic.verified/aichatweb/Services/SemanticSearch.cs
  test/ProjectTemplates/Microsoft.Extensions.AI.Templates.IntegrationTests/Snapshots/aichatweb.BasicAspire--aspire.verified/aichatweb/aichatweb.Web/Services/SemanticSearch.cs
Labels: area-ai

#6296 Augment FunctionInvokingChatClient's span with token counts
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
Labels: area-ai

#6300 Rename ChatThreadId to ConversationId
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/CachingChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatResponse{T}.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatOptionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/ChatCompletion/ChatResponseUpdateExtensionsTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIResponseClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
Labels: area-ai

#6299 Repackage azure-devops-extensions-api to fix Azure DevOps report plugin
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/.gitignore
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Build/Build.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Build/BuildClient.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Build/index.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/Client.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/CommonServices.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/Context.d.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/Fetch.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/RestClientBase.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/Util/Serialization.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/Util/Url.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Common/index.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Core/Core.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/Core/index.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/azure-devops-extension-api/index.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/main.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/vite.config.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/build-if-out-of-date.js
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ChatDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ConversationDetails.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/DiagnosticsContent.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/MetricDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ReportContext.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScenarioRunHistory.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScoreDetail.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScoreNodeHistory.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Styles.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package-lock.json
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package.json
Labels: area-ai-eval

#6301 Fix build error
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScenarioTree.tsx
Labels: area-ai-eval

#6258 Add note on extending timeout for Ollama client
  src/ProjectTemplates/Microsoft.Extensions.AI.Templates/src/ChatWithCustomData/README.Aspire.md
Labels: area-ai-templates

#6289 Improve CPU metrics calculations for CgroupV2
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/ILinuxUtilizationParser.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV1.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationParserCgroupV2.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/Log.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringOptions.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/AcceptanceTest.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationParserCgroupV1Tests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationParserCgroupV2Tests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationProviderTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Resources/DummyLinuxUtilizationParser.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Fallsback_To_Cpuset_When_Quota_And_Period_Are_Minus_One_.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=           12_period=eeeee 12.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=-----_period=18.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=-18_period=18.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=-_period=d'.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=-_period=d--.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=12       _period=.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=123_period=-----.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=2_period=d--.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=2d2d2d_period=e3.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=3d_period=d3.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Files_Contain_Invalid_Data_quota=dd1d_period=18.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Weight_Files_Contain_Invalid_Data_content=-1.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Weight_Files_Contain_Invalid_Data_content=0.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Weight_Files_Contain_Invalid_Data_content=10001.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Cgroup_Cpu_Weight_Files_Contain_Invalid_Data_content=dasrz3424.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuAcctUsage_Has_Invalid_Content_Both_Parts_content=@#dddada_value=342322.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuAcctUsage_Has_Invalid_Content_Both_Parts_content=dasd_value=-1.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuAcctUsage_Has_Invalid_Content_Both_Parts_content=usage__value=12222.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=    d  182-1923.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=--.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=-11.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=0-.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=1-18                   --.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=1-18-22.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=22-18.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=22-d.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=aaaa.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuSet_Has_Invalid_Content_content=d-22.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=  2.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=  2569530 36700 245693 4860924 82283 0 4360 0dsa.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=  2569530 36700 245693.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=2569530367000.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=asdasd  2569530 36700 245693 4860924 82283 0 4360 0 0 0.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_CpuUsage_Invalid_content=cpu  2569530 36700 245693.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Usage_Usec_Has_Negative_Value_value=-1.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Usage_Usec_Has_Negative_Value_value=-15.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/Verified/LinuxUtilizationParserCgroupV2Tests.Throws_When_Usage_Usec_Has_Negative_Value_value=-32131.verified.txt
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/ResourceMonitoringOptionsTests.cs
Labels: area-telemetry

#6304 Restore deleted members as obsolete
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatOptions.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponse.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/ChatCompletion/ChatResponseUpdate.cs
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Embeddings/EmbeddingGeneratorExtensions.cs
Labels: area-ai

#6308 move to AwesomeAssertions
  eng/packages/TestOnly.props
  test/Directory.Build.targets
Labels: area-infrastructure

#6310 Support [FromKeyedServices] in AIFunctionFactory
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-ai

#6316 Introduce Context property on EvaluationMetric
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/Program.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ChatConversationEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/EquivalenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/GroundednessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceTruthAndCompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/SingleNumericMetricEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ConversationDetails.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/EvalTypes.d.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScoreDetail.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Styles.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/EvaluationMetricExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/GroundednessProEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/UngroundedAttributesEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/CompositeEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationMetric.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationMetricExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationResultExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/ResultsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/ResultStoreTester.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Tests/ScenarioRunResultTests.cs
Labels: area-ai-eval

#6317 Utilize IServiceProviderIsService in AIFunctionFactory
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactory.cs
  src/Libraries/Microsoft.Extensions.AI/Functions/AIFunctionFactoryOptions.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/Functions/AIFunctionFactoryTest.cs
Labels: area-ai

#6321 Fix Process Metric calculation in CgroupsV2
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/LinuxUtilizationProvider.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Linux/Log.cs
  src/Shared/Instruments/ResourceUtilizationInstruments.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Linux/LinuxUtilizationProviderTests.cs
Labels: area-telemetry

#6320 Remove the abstraction for token counting from the main evaluation API
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/ChatConversationEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/CoherenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/EquivalenceEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/FluencyEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/GroundednessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/RelevanceTruthAndCompletenessEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/Utilities/JsonOutputFixer.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Azure/Storage/AzureStorageReportingConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ReportingConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/ScenarioRun.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/Storage/DiskBasedReportingConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyServiceConfigurationExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/Microsoft.Extensions.AI.Evaluation.Safety.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation/ChatConfiguration.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/CompositeEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluatorExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/IEvaluationTokenCounter.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/IEvaluator.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/Microsoft.Extensions.AI.Evaluation.csproj
  src/Libraries/Microsoft.Extensions.AI.Evaluation/TokenizerExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Microsoft.Extensions.AI.Evaluation.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/QualityEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/ResultsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/SafetyEvaluatorTests.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Setup.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Tests/ChatMessageUtilities.cs
Labels: area-ai-eval

#6327 Remove AsChatClient/AsEmbeddingGenerator APIs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIClientExtensions.cs
Labels: area-ai

#6285 Disable default required property schema generation and OpenAI strict mode.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonSchemaCreateOptions.cs
  src/Libraries/Microsoft.Extensions.AI.AzureAIInference/AzureAIInferenceChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/ChatClientStructuredOutputExtensions.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
  test/Libraries/Microsoft.Extensions.AI.AzureAIInference.Tests/AzureAIInferenceChatClientTests.cs
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/OpenAIChatClientTests.cs
Labels: area-ai

#6329 Accessibility fixes for the HTML report
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/App.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/azure-devops-report/src/main.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.css
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/App.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ChatDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ConversationDetails.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/DiagnosticsContent.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/MetricCard.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/MetricDetailsSection.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScenarioRunHistory.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/ScoreDetail.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/Styles.ts
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/TagsDisplay.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/html-report/src/main.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package-lock.json
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/package.json
Labels: area-ai-eval

#6181 Add Windows disk I/O metrics to ResourceMonitoring
  eng/MSBuild/LegacySupport.props
  src/LegacySupport/PlatformAttributes/PlatformAttributes.cs
  src/LegacySupport/PlatformAttributes/README.md
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Microsoft.Extensions.Diagnostics.ResourceMonitoring.csproj
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringOptions.Windows.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/ResourceMonitoringServiceCollectionExtensions.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Disk/WindowsDiskIoRatePerfCounter.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Disk/WindowsDiskMetrics.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Disk/WindowsDiskPerfCounterNames.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/IPerformanceCounter.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/IPerformanceCounterFactory.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/Network/WindowsNetworkMetrics.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/PerformanceCounterFactory.cs
  src/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring/Windows/PerformanceCounterWrapper.cs
  src/Shared/Instruments/ResourceUtilizationInstruments.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/Disk/WindowsDiskIoRatePerfCounterTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/Disk/WindowsDiskMetricsTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/FakePerformanceCounter.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/PerformanceCounterFactoryTests.cs
  test/Libraries/Microsoft.Extensions.Diagnostics.ResourceMonitoring.Tests/Windows/PerformanceCounterWrapperTests.cs
Labels: area-resourcemonitoring

#6340 A couple of minor fixes
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/TypeScript/components/MetricCard.tsx
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/ContentSafetyService.UrlCacheKey.cs
Labels: area-ai-eval

#6345 Update readmes
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Console/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Quality/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting.Azure/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Reporting/CSharp/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation.Safety/README.md
  src/Libraries/Microsoft.Extensions.AI.Evaluation/EvaluationMetricExtensions.cs
  src/Libraries/Microsoft.Extensions.AI.Evaluation/README.md
Labels: area-ai-eval

#6346 Expose AIContent constructor
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Contents/AIContent.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Contents/AIContentTests.cs
Labels: area-ai

#6344 Add PDF support to OpenAI AsIChatClient
  eng/packages/TestOnly.props
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIChatClient.cs
  src/Libraries/Microsoft.Extensions.AI.OpenAI/OpenAIResponseChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Evaluation.Integration.Tests/Microsoft.Extensions.AI.Evaluation.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/ChatClientIntegrationTests.cs
  test/Libraries/Microsoft.Extensions.AI.Integration.Tests/Microsoft.Extensions.AI.Integration.Tests.csproj
  test/Libraries/Microsoft.Extensions.AI.OpenAI.Tests/Microsoft.Extensions.AI.OpenAI.Tests.csproj
  test/Shared/ImageDataUri/ImageDataUri.cs
  test/Shared/Shared.Tests.csproj
Labels: area-ai

#6348 Make `CreateJsonSchema` tolerate JSO inputs that don't have a resolver set.
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Utilities/AIJsonUtilities.Schema.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Utilities/AIJsonUtilitiesTests.cs
Labels: area-ai

#6325 Enhance Function Invocation Extensibility for Microsoft.Extensions.AI
  src/Libraries/Microsoft.Extensions.AI.Abstractions/Functions/AIFunctionArguments.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvocationContext.cs
  src/Libraries/Microsoft.Extensions.AI/ChatCompletion/FunctionInvokingChatClient.cs
  test/Libraries/Microsoft.Extensions.AI.Abstractions.Tests/Functions/AIFunctionArgumentsTests.cs
  test/Libraries/Microsoft.Extensions.AI.Tests/ChatCompletion/FunctionInvokingChatClientTests.cs
Labels: area-ai
